/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for appendOrderItem changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the appendOrderItem service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AppendOrderItemRequest extends RequestBase {

    private String orderId;
    private String shipGroupSeqId;
    private String productId;
    private String prodCatalogId;
    private double basePrice;
    private double quantity;
    private double amount;
    private String overridePrice;
    private String reasonEnumId;
    private String orderItemTypeId;
    private String changeComments;
    private Timestamp itemDesiredDeliveryDate;
    private Map<String, Object> itemAttributesMap;
    private Boolean calcTax;
}
