/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for cancelOrderItem changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the cancelOrderItem service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CancelOrderItemRequest extends RequestBase {

    private String orderId;
    private String orderItemSeqId;
    private String shipGroupSeqId;
    private double cancelQuantity;
    private Map<String, Object> itemReasonMap;
    private Map<String, Object> itemCommentMap;
    private Map<String, Object> itemQtyMap;
}
