/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for copyQuote changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the copyQuote service.
 * Generated from OFBiz service definition; default-entity-name=Quote.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CopyQuoteRequest extends RequestBase {

    private String quoteId;
    private String copyQuoteRoles;
    private String copyQuoteAttributes;
    private String copyQuoteCoefficients;
    private String copyQuoteItems;
    private String copyQuoteAdjustments;
    private String copyQuoteTerms;
}
