/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createShoppingListItem changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createShoppingListItem service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateShoppingListItemRequest extends RequestBase {

    private String shoppingListId;
    private String productId;
    private double quantity;
    private double modifiedPrice;
    private Timestamp reservStart;
    private double reservLength;
    private double reservPersons;
    private double quantityPurchased;
    private String configId;
    private String productStoreId;
    private Map<String, Object> shoppingListItemAttributes;
}
