/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCustRequestItem changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createCustRequestItem service.
 * Generated from OFBiz service definition; default-entity-name=CustRequestItem.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCustRequestItemRequest extends RequestBase {

    private String custRequestId;
    private String custRequestItemSeqId;
    private String custRequestResolutionId;
    private String statusId;
    private Double priority;
    private Double sequenceNum;
    private Timestamp requiredByDate;
    private String productId;
    private Double quantity;
    private Double selectedAmount;
    private Double maximumAmount;
    private Timestamp reservStart;
    private Double reservLength;
    private Double reservPersons;
    private String configId;
    private String description;
    private String story;
}
