/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createAllocationPlanAndItems changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createAllocationPlanAndItems service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateAllocationPlanAndItemsRequest extends RequestBase {

    private String productId;
    private String planName;
    private Integer itemListSize;
    private Map<String, Object> itemOrderIdMap;
    private Map<String, Object> itemOrderItemSeqIdMap;
    private Map<String, Object> itemAllocatedQuantityMap;
}
