/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCustRequestItem changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createCustRequestItem service.
 * Generated from OFBiz service definition; default-entity-name=CustRequestItem.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCustRequestItemResponse extends ResponseBase {

    private String custRequestId;
    private String custRequestItemSeqId;
}
