/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCustRequestItemNote changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createCustRequestItemNote service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCustRequestItemNoteRequest extends RequestBase {

    private String custRequestId;
    private String custRequestItemSeqId;
    private String note;
    private String partyId;
}
