/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createQuoteAndQuoteItemForRequest changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createQuoteAndQuoteItemForRequest service.
 * Generated from OFBiz service definition; default-entity-name=QuoteItem.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateQuoteAndQuoteItemForRequestRequest extends RequestBase {

    private String productId;
    private String productFeatureId;
    private String deliverableTypeId;
    private String skillTypeId;
    private String uomId;
    private String workEffortId;
    private String custRequestId;
    private String custRequestItemSeqId;
    private Double quantity;
    private Double selectedAmount;
    private Double quoteUnitPrice;
    private Timestamp reservStart;
    private Double reservLength;
    private Double reservPersons;
    private String configId;
    private Timestamp estimatedDeliveryDate;
    private String comments;
    private String isPromo;
    private Double leadTimeDays;
}
