/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createQuoteAttribute changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createQuoteAttribute service.
 * Generated from OFBiz service definition; default-entity-name=QuoteAttribute.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateQuoteAttributeRequest extends RequestBase {

    private String quoteId;
    private String attrName;
    private String attrValue;
    private String attrDescription;
}
