/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createOrderDeliverySchedule changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createOrderDeliverySchedule service.
 * Generated from OFBiz service definition; default-entity-name=OrderDeliverySchedule.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateOrderDeliveryScheduleRequest extends RequestBase {

    private String orderId;
    private String orderItemSeqId;
    private Timestamp estimatedReadyDate;
    private Double cartons;
    private Double skidsPallets;
    private Double unitsPieces;
    private Double totalCubicSize;
    private String totalCubicUomId;
    private Double totalWeight;
    private String totalWeightUomId;
    private String statusId;
}
