/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createQuoteTerm changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createQuoteTerm service.
 * Generated from OFBiz service definition; default-entity-name=QuoteTerm.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateQuoteTermRequest extends RequestBase {

    private String termTypeId;
    private String quoteId;
    private String quoteItemSeqId;
    private Double termValue;
    private String uomId;
    private Double termDays;
    private String textValue;
    private String description;
}
