/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createQuoteCoefficient changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createQuoteCoefficient service.
 * Generated from OFBiz service definition; default-entity-name=QuoteCoefficient.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateQuoteCoefficientRequest extends RequestBase {

    private String quoteId;
    private String coeffName;
    private Double coeffValue;
}
