/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createOrderAdjustment changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createOrderAdjustment service.
 * Generated from OFBiz service definition; default-entity-name=OrderAdjustment.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateOrderAdjustmentRequest extends RequestBase {

    private String orderAdjustmentTypeId;
    private String orderId;
    private String orderItemSeqId;
    private String shipGroupSeqId;
    private String comments;
    private String description;
    private Double amount;
    private Double recurringAmount;
    private Double amountAlreadyIncluded;
    private String productPromoId;
    private String productPromoRuleId;
    private String productPromoActionSeqId;
    private String productFeatureId;
    private String correspondingProductId;
    private String taxAuthorityRateSeqId;
    private String sourceReferenceId;
    private Double sourcePercentage;
    private String customerReferenceId;
    private String primaryGeoId;
    private String secondaryGeoId;
    private Double exemptAmount;
    private String taxAuthGeoId;
    private String taxAuthPartyId;
    private String overrideGlAccountId;
    private String includeInTax;
    private String includeInShipping;
    private String isManual;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private String originalAdjustmentId;
}
