/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createShoppingListItem changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createShoppingListItem service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateShoppingListItemResponse extends ResponseBase {

    private String productStoreId;
    private String shoppingListItemSeqId;
}
