/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for expireCustRequestContent changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the expireCustRequestContent service.
 * Generated from OFBiz service definition; default-entity-name=CustRequestContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ExpireCustRequestContentRequest extends RequestBase {

    private String custRequestId;
    private String contentId;
    private Timestamp fromDate;
    private Timestamp thruDate;
}
