/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for findOrders changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the findOrders service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class FindOrdersRequest extends RequestBase {

    private String orderId;
    private String orderName;
    private List<Object> orderTypeId;
    private List<Object> orderStatusId;
    private List<Object> productStoreId;
    private List<Object> orderWebSiteId;
    private List<Object> salesChannelEnumId;
    private String createdBy;
    private String terminalId;
    private String transactionId;
    private String externalId;
    private String internalCode;
    private String useEntryDate;
    private String minDate;
    private String maxDate;
    private String hasBackOrders;
    private List<Object> roleTypeId;
    private String partyId;
    private String correspondingPoId;
    private String subscriptionId;
    private String productId;
    private String budgetId;
    private String quoteId;
    private String goodIdentificationTypeId;
    private String goodIdentificationIdValue;
    private String billingAccountId;
    private String finAccountId;
    private String cardNumber;
    private String accountNumber;
    private String paymentStatusId;
    private String inventoryItemId;
    private String softIdentifier;
    private String serialNumber;
    private String shipmentId;
    private String filterInventoryProblems;
    private String filterPOsWithRejectedItems;
    private String filterPOsOpenPastTheirETA;
    private String filterPartiallyReceivedPOs;
    private String isViewed;
    private String shipmentMethod;
    private String gatewayAvsResult;
    private String gatewayScoreResult;
    private String countryGeoId;
    private String includeCountry;
    private Integer viewIndex;
    private Integer viewSize;
    private String showAll;
}
