/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for findOrders changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.ResponseBase;

import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the findOrders service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class FindOrdersResponse extends ResponseBase {

    private Integer viewIndex;
    private Integer viewSize;
    private String showAll;
    private Integer highIndex;
    private Integer lowIndex;
    private List<String> filterInventoryProblemsList;
    private List<String> filterPOsWithRejectedItemsList;
    private List<String> filterPOsOpenPastTheirETAList;
    private List<String> filterPartiallyReceivedPOsList;
    private String paramList;
    private List<String> orderList;
    private Integer orderListSize;
}
