/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for sendOrderConfirmation changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the sendOrderConfirmation service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SendOrderConfirmationRequest extends RequestBase {

    private String orderId;
    private String orderItemSeqId;
    private String screenUri;
    private String comments;
    private String sendTo;
    private String sendCc;
    private String sendBcc;
    private String note;
    private Object temporaryAnonymousUserLogin;
}
