/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for setCartShippingOptions changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the setCartShippingOptions service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SetCartShippingOptionsRequest extends RequestBase {

    private Object shoppingCart;
    private Integer groupIndex;
    private String shippingContactMechId;
    private String shipmentMethodString;
    private String shippingInstructions;
    private Boolean maySplit;
    private Boolean isGift;
    private String giftMessage;
}
