/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateOrderPaymentPreference changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateOrderPaymentPreference service.
 * Generated from OFBiz service definition; default-entity-name=OrderPaymentPreference.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateOrderPaymentPreferenceRequest extends RequestBase {

    private String orderPaymentPreferenceId;
    private String orderId;
    private String orderItemSeqId;
    private String shipGroupSeqId;
    private String productPricePurposeId;
    private String paymentMethodTypeId;
    private String paymentMethodId;
    private String finAccountId;
    private String securityCode;
    private String track2;
    private String presentFlag;
    private String swipedFlag;
    private String overflowFlag;
    private Double maxAmount;
    private Double processAttempt;
    private String billingPostalCode;
    private String manualAuthCode;
    private String manualRefNum;
    private String statusId;
    private String needsNsfRetry;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private String checkOutPaymentId;
}
