/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateQuote changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateQuote service.
 * Generated from OFBiz service definition; default-entity-name=Quote.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateQuoteRequest extends RequestBase {

    private String quoteId;
    private String quoteTypeId;
    private String partyId;
    private Timestamp issueDate;
    private String statusId;
    private String currencyUomId;
    private String productStoreId;
    private String salesChannelEnumId;
    private Timestamp validFromDate;
    private Timestamp validThruDate;
    private String quoteName;
    private String description;
}
