/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateOrderItems changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateOrderItems service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateOrderItemsRequest extends RequestBase {

    private String orderId;
    private String supplierPartyId;
    private String orderTypeId;
    private Boolean calcTax;
    private Map<String, Object> itemDescriptionMap;
    private Map<String, Object> itemQtyMap;
    private Map<String, Object> itemPriceMap;
    private Map<String, Object> overridePriceMap;
    private Map<String, Object> itemReasonMap;
    private Map<String, Object> itemCommentMap;
    private Map<String, Object> itemAttributesMap;
    private Map<String, Object> itemShipDateMap;
    private Map<String, Object> itemDeliveryDateMap;
    private Map<String, Object> itemReserveAfterDateMap;
}
