/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateAllocationPlanItems changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateAllocationPlanItems service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateAllocationPlanItemsRequest extends RequestBase {

    private String planId;
    private Map<String, Object> orderIdMap;
    private Map<String, Object> orderItemSeqIdMap;
    private Map<String, Object> productIdMap;
    private Map<String, Object> prioritySeqIdMap;
    private Map<String, Object> allocatedQuantityMap;
    private Map<String, Object> rowSubmitMap;
}
