/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateShippingMethodAndCharges changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateShippingMethodAndCharges service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateShippingMethodAndChargesRequest extends RequestBase {

    private String orderId;
    private String shipGroupSeqId;
    private String oldContactMechId;
    private String shipmentMethodAndAmount;
    private String contactMechPurposeTypeId;
    private String orderAdjustmentId;
    private String shippingAmount;
    private String shipmentId;
    private String shipmentRouteSegmentId;
}
