/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateRequirement changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateRequirement service.
 * Generated from OFBiz service definition; default-entity-name=Requirement.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateRequirementRequest extends RequestBase {

    private String requirementId;
    private String requirementTypeId;
    private String facilityId;
    private String deliverableId;
    private String fixedAssetId;
    private String productId;
    private String statusId;
    private String description;
    private Timestamp requirementStartDate;
    private Timestamp requiredByDate;
    private Double estimatedBudget;
    private Double quantity;
    private String useCase;
    private String reason;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private String facilityIdTo;
}
