/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateReturnHeader changes.
 */
package com.landawn.ofbiz.model.order;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateReturnHeader service.
 * Generated from OFBiz service definition; default-entity-name=ReturnHeader.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateReturnHeaderRequest extends RequestBase {

    private String returnId;
    private String returnHeaderTypeId;
    private String statusId;
    private String createdBy;
    private String fromPartyId;
    private String toPartyId;
    private String paymentMethodId;
    private String finAccountId;
    private String billingAccountId;
    private Timestamp entryDate;
    private String originContactMechId;
    private String destinationFacilityId;
    private String needsInventoryReceive;
    private String currencyUomId;
    private String supplierRmaId;
}
