/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for addProductionRunRoutingTask changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the addProductionRunRoutingTask service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AddProductionRunRoutingTaskRequest extends RequestBase {

    private String productionRunId;
    private String routingTaskId;
    private Long priority;
    private double estimatedSetupMillis;
    private double estimatedMilliSeconds;
    private String workEffortName;
    private String description;
    private Timestamp estimatedStartDate;
    private Timestamp estimatedCompletionDate;
}
