/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for changeProductionRunTaskStatus changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the changeProductionRunTaskStatus service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ChangeProductionRunTaskStatusResponse extends ResponseBase {

    private String oldStatusId;
    private String newStatusId;
}
