/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCalendarExceptionDay changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createCalendarExceptionDay service.
 * Generated from OFBiz service definition; default-entity-name=TechDataCalendarExcDay.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCalendarExceptionDayRequest extends RequestBase {

    private String calendarId;
    private Timestamp exceptionDateStartTime;
    private Double exceptionCapacity;
    private Double usedCapacity;
    private String description;
}
