/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCalendarWeek changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Time;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createCalendarWeek service.
 * Generated from OFBiz service definition; default-entity-name=TechDataCalendarWeek.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCalendarWeekRequest extends RequestBase {

    private String calendarWeekId;
    private String description;
    private Time mondayStartTime;
    private Double mondayCapacity;
    private Time tuesdayStartTime;
    private Double tuesdayCapacity;
    private Time wednesdayStartTime;
    private Double wednesdayCapacity;
    private Time thursdayStartTime;
    private Double thursdayCapacity;
    private Time fridayStartTime;
    private Double fridayCapacity;
    private Time saturdayStartTime;
    private Double saturdayCapacity;
    private Time sundayStartTime;
    private Double sundayCapacity;
}
