/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for productionRunDeclareAndProduce changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;

import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the productionRunDeclareAndProduce service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ProductionRunDeclareAndProduceRequest extends RequestBase {

    private String workEffortId;
    private double quantity;
    private String quantityUomId;
    private String inventoryItemTypeId;
    private String locationSeqId;
    private String lotId;
    private Boolean createLotIfNeeded;
    private Boolean autoCreateLot;
    private Map<String, Object> componentsLocationMap;
}
