/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for reallocateAndIssueInventory changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;

import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the reallocateAndIssueInventory service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ReallocateAndIssueInventoryRequest extends RequestBase {

    private String workEffortId;
    private String productId;
    private String reserveOrderEnumId;
    private List<Object> inventoryIssuePlan;
    private List<String> impactList;
    private String productionRunId;
    private String failIfItemsAreNotAvailable;
    private String failIfItemsAreNotOnHand;
}
