/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for releaseProductionRunTaskComponent changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the releaseProductionRunTaskComponent service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ReleaseProductionRunTaskComponentRequest extends RequestBase {

    private String workEffortId;
    private String inventoryItemId;
    private String productId;
    private double quantity;
    private Boolean appendInventoryItemDetail;
}
