/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeCalendarExceptionWeek changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeCalendarExceptionWeek service.
 * Generated from OFBiz service definition; default-entity-name=TechDataCalendarExcWeek.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveCalendarExceptionWeekRequest extends RequestBase {

    private String calendarId;
    private Date exceptionDateStart;
}
