/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeCalendar changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeCalendar service.
 * Generated from OFBiz service definition; default-entity-name=TechDataCalendar.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveCalendarRequest extends RequestBase {

    private String calendarId;
}
