/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for reserveWorkEffortInventoryItem changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the reserveWorkEffortInventoryItem service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ReserveWorkEffortInventoryItemRequest extends RequestBase {

    private String workEffortId;
    private String productId;
    private String facilityId;
    private double quantity;
    private double quantityNotAvailable;
    private String inventoryItemId;
    private String requireInventory;
    private String reserveOrderEnumId;
    private String lotId;
}
