/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductionRunTask changes.
 */
package com.landawn.ofbiz.model.manufacturing;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductionRunTask service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductionRunTaskRequest extends RequestBase {

    private String productionRunId;
    private String productionRunTaskId;
    private String partyId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private double addQuantityProduced;
    private double addQuantityRejected;
    private double addSetupTime;
    private double addTaskTime;
    private String comments;
    private Boolean issueRequiredComponents;
    private Map<String, Object> componentsLocationMap;
}
