/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for addFixedAssetProduct changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the addFixedAssetProduct service.
 * Generated from OFBiz service definition; default-entity-name=FixedAssetProduct.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AddFixedAssetProductRequest extends RequestBase {

    private String fixedAssetId;
    private String productId;
    private String fixedAssetProductTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String comments;
    private Double sequenceNum;
    private Double quantity;
    private String quantityUomId;
}
