/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for copyAgreement changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the copyAgreement service.
 * Generated from OFBiz service definition; default-entity-name=Agreement.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CopyAgreementRequest extends RequestBase {

    private String agreementId;
    private String copyAgreementTerms;
    private String copyAgreementProducts;
    private String copyAgreementParties;
    private String copyAgreementFacilities;
}
