/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createFinAccount changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createFinAccount service.
 * Generated from OFBiz service definition; default-entity-name=FinAccount.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateFinAccountRequest extends RequestBase {

    private String finAccountId;
    private String finAccountTypeId;
    private String statusId;
    private String finAccountName;
    private String finAccountCode;
    private String finAccountPin;
    private String currencyUomId;
    private String organizationPartyId;
    private String ownerPartyId;
    private String postToGlAccountId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String isRefundable;
    private String replenishPaymentId;
    private Double replenishLevel;
}
