/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createFixedAssetMaintOrder changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createFixedAssetMaintOrder service.
 * Generated from OFBiz service definition; default-entity-name=FixedAssetMaintOrder.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateFixedAssetMaintOrderRequest extends RequestBase {

    private String fixedAssetId;
    private String maintHistSeqId;
    private String orderId;
    private String orderItemSeqId;
}
