/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createAcctgTransEntry changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createAcctgTransEntry service.
 * Generated from OFBiz service definition; default-entity-name=AcctgTransEntry.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateAcctgTransEntryRequest extends RequestBase {

    private String acctgTransEntryTypeId;
    private String description;
    private String voucherRef;
    private String partyId;
    private String roleTypeId;
    private String theirPartyId;
    private String productId;
    private String theirProductId;
    private String inventoryItemId;
    private String glAccountTypeId;
    private String glAccountId;
    private String organizationPartyId;
    private Double amount;
    private String currencyUomId;
    private Double origAmount;
    private String origCurrencyUomId;
    private String debitCreditFlag;
    private Date dueDate;
    private String groupId;
    private String taxId;
    private String settlementTermId;
    private String isSummary;
    private String acctgTransId;
    private String purposeEnumId;
}
