/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPaymentApplication changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createPaymentApplication service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePaymentApplicationRequest extends RequestBase {

    private String paymentId;
    private String toPaymentId;
    private String invoiceId;
    private String billingAccountId;
    private String taxAuthGeoId;
    private double amountApplied;
}
