/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createBudgetReview changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createBudgetReview service.
 * Generated from OFBiz service definition; default-entity-name=BudgetReview.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateBudgetReviewRequest extends RequestBase {

    private String budgetId;
    private String partyId;
    private String budgetReviewResultTypeId;
    private Timestamp reviewDate;
}
