/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createFixedAsset changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Date;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createFixedAsset service.
 * Generated from OFBiz service definition; default-entity-name=FixedAsset.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateFixedAssetRequest extends RequestBase {

    private String fixedAssetId;
    private String fixedAssetTypeId;
    private String parentFixedAssetId;
    private String instanceOfProductId;
    private String classEnumId;
    private String partyId;
    private String roleTypeId;
    private String fixedAssetName;
    private String acquireOrderId;
    private String acquireOrderItemSeqId;
    private Timestamp dateAcquired;
    private Timestamp dateLastServiced;
    private Timestamp dateNextService;
    private Date expectedEndOfLife;
    private Date actualEndOfLife;
    private Double productionCapacity;
    private String uomId;
    private String calendarId;
    private String serialNumber;
    private String locatedAtFacilityId;
    private String locatedAtLocationSeqId;
    private Double salvageValue;
    private Double depreciation;
    private Double purchaseCost;
    private String purchaseCostUomId;
}
