/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPaymentGroup changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createPaymentGroup service.
 * Generated from OFBiz service definition; default-entity-name=PaymentGroup.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePaymentGroupResponse extends ResponseBase {

    private String paymentGroupId;
}
