/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createBillingAccountTerm changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createBillingAccountTerm service.
 * Generated from OFBiz service definition; default-entity-name=BillingAccountTerm.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateBillingAccountTermRequest extends RequestBase {

    private String billingAccountId;
    private String termTypeId;
    private Double termValue;
    private Double termDays;
    private String uomId;
}
