/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPartyPrefDocTypeTpl changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createPartyPrefDocTypeTpl service.
 * Generated from OFBiz service definition; default-entity-name=PartyPrefDocTypeTpl.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePartyPrefDocTypeTplResponse extends ResponseBase {

    private String partyPrefDocTypeTplId;
}
