/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPartyTaxAuthInfo changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createPartyTaxAuthInfo service.
 * Generated from OFBiz service definition; default-entity-name=PartyTaxAuthInfo.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePartyTaxAuthInfoRequest extends RequestBase {

    private String partyId;
    private String taxAuthGeoId;
    private String taxAuthPartyId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String partyTaxId;
    private String isExempt;
    private String isNexus;
}
