/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createGlReconciliation changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createGlReconciliation service.
 * Generated from OFBiz service definition; default-entity-name=GlReconciliation.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateGlReconciliationRequest extends RequestBase {

    private String glReconciliationName;
    private String description;
    private Timestamp createdDate;
    private Timestamp lastModifiedDate;
    private String glAccountId;
    private String statusId;
    private String organizationPartyId;
    private Double reconciledBalance;
    private Double openingBalance;
    private Timestamp reconciledDate;
}
