/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createGlAccountCategoryMember changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createGlAccountCategoryMember service.
 * Generated from OFBiz service definition; default-entity-name=GlAccountCategoryMember.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateGlAccountCategoryMemberRequest extends RequestBase {

    private String glAccountId;
    private String glAccountCategoryId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double amountPercentage;
}
