/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCostComponentCalc changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createCostComponentCalc service.
 * Generated from OFBiz service definition; default-entity-name=CostComponentCalc.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCostComponentCalcResponse extends ResponseBase {

    private String costComponentCalcId;
}
