/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createFinAccountTrans changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createFinAccountTrans service.
 * Generated from OFBiz service definition; default-entity-name=FinAccountTrans.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateFinAccountTransRequest extends RequestBase {

    private String finAccountTransTypeId;
    private String finAccountId;
    private String partyId;
    private String glReconciliationId;
    private Timestamp transactionDate;
    private Timestamp entryDate;
    private Double amount;
    private String paymentId;
    private String orderId;
    private String orderItemSeqId;
    private String reasonEnumId;
    private String comments;
    private String statusId;
    private String glAccountId;
}
