/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deletePartyGlAccount changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deletePartyGlAccount service.
 * Generated from OFBiz service definition; default-entity-name=PartyGlAccount.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeletePartyGlAccountRequest extends RequestBase {

    private String organizationPartyId;
    private String partyId;
    private String roleTypeId;
    private String glAccountTypeId;
}
