/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteTaxAuthorityRateProduct changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteTaxAuthorityRateProduct service.
 * Generated from OFBiz service definition; default-entity-name=TaxAuthorityRateProduct.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteTaxAuthorityRateProductRequest extends RequestBase {

    private String taxAuthorityRateSeqId;
}
