/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for expirePaymentGroupMember changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the expirePaymentGroupMember service.
 * Generated from OFBiz service definition; default-entity-name=PaymentGroupMember.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ExpirePaymentGroupMemberRequest extends RequestBase {

    private String paymentGroupId;
    private String paymentId;
    private Timestamp fromDate;
}
