/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for manualForcedCcTransaction changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the manualForcedCcTransaction service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ManualForcedCcTransactionRequest extends RequestBase {

    private String paymentMethodTypeId;
    private String productStoreId;
    private String transactionType;
    private String companyNameOnCard;
    private String titleOnCard;
    private String firstNameOnCard;
    private String middleNameOnCard;
    private String lastNameOnCard;
    private String suffixOnCard;
    private String cardType;
    private String cardNumber;
    private String cardSecurityCode;
    private String expMonth;
    private String expYear;
    private String infoString;
    private String address1;
    private String address2;
    private String city;
    private String stateProvinceGeoId;
    private String postalCode;
    private String countryGeoId;
    private double amount;
    private String referenceCode;
    private String orderPaymentPreferenceId;
}
