/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for quickCreateAcctgTransAndEntries changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Date;
import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the quickCreateAcctgTransAndEntries service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class QuickCreateAcctgTransAndEntriesRequest extends RequestBase {

    private String acctgTransTypeId;
    private String description;
    private Timestamp transactionDate;
    private String isPosted;
    private Timestamp postedDate;
    private Timestamp scheduledPostingDate;
    private String glJournalId;
    private String glFiscalTypeId;
    private String voucherRef;
    private Timestamp voucherDate;
    private String groupStatusId;
    private String fixedAssetId;
    private String inventoryItemId;
    private String physicalInventoryId;
    private String partyId;
    private String roleTypeId;
    private String invoiceId;
    private String paymentId;
    private String finAccountTransId;
    private String shipmentId;
    private String receiptId;
    private String workEffortId;
    private String theirAcctgTransId;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private String acctgTransEntryTypeId;
    private String theirPartyId;
    private String productId;
    private String theirProductId;
    private String glAccountTypeId;
    private String organizationPartyId;
    private Double amount;
    private String currencyUomId;
    private Double origAmount;
    private String origCurrencyUomId;
    private Date dueDate;
    private String groupId;
    private String taxId;
    private String reconcileStatusId;
    private String settlementTermId;
    private String isSummary;
    private String debitGlAccountId;
    private String creditGlAccountId;
}
