/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removePaymentMethodTypeGlAssignment changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removePaymentMethodTypeGlAssignment service.
 * Generated from OFBiz service definition; default-entity-name=PaymentMethodTypeGlAccount.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemovePaymentMethodTypeGlAssignmentRequest extends RequestBase {

    private String paymentMethodTypeId;
    private String organizationPartyId;
}
