/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeAgreementContent changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeAgreementContent service.
 * Generated from OFBiz service definition; default-entity-name=AgreementContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveAgreementContentRequest extends RequestBase {

    private String agreementId;
    private String agreementItemSeqId;
    private String agreementContentTypeId;
    private String contentId;
    private Timestamp fromDate;
}
