/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removePaymentApplication changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the removePaymentApplication service.
 * Generated from OFBiz service definition; default-entity-name=PaymentApplication.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemovePaymentApplicationResponse extends ResponseBase {

    private String paymentId;
    private String invoiceId;
    private String invoiceItemSeqId;
    private String billingAccountId;
    private String overrideGlAccountId;
    private String toPaymentId;
    private String taxAuthGeoId;
    private Double amountApplied;
}
