/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeAgreementPartyApplic changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeAgreementPartyApplic service.
 * Generated from OFBiz service definition; default-entity-name=AgreementPartyApplic.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveAgreementPartyApplicRequest extends RequestBase {

    private String agreementId;
    private String agreementItemSeqId;
    private String partyId;
}
