/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateRateAmount changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateRateAmount service.
 * Generated from OFBiz service definition; default-entity-name=RateAmount.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateRateAmountRequest extends RequestBase {

    private String rateTypeId;
    private String rateCurrencyUomId;
    private String periodTypeId;
    private String workEffortId;
    private String partyId;
    private String emplPositionTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double rateAmount;
}
