/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePaymentGatewayConfigClearCommerce changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePaymentGatewayConfigClearCommerce service.
 * Generated from OFBiz service definition; default-entity-name=PaymentGatewayClearCommerce.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePaymentGatewayConfigClearCommerceRequest extends RequestBase {

    private String paymentGatewayConfigId;
    private String sourceId;
    private String groupId;
    private String clientId;
    private String username;
    private String pwd;
    private String userAlias;
    private String effectiveAlias;
    private String processMode;
    private String serverUrl;
    private String enableCvm;
}
