/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateGlAccountCategory changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateGlAccountCategory service.
 * Generated from OFBiz service definition; default-entity-name=GlAccountCategory.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateGlAccountCategoryRequest extends RequestBase {

    private String glAccountCategoryId;
    private String glAccountCategoryTypeId;
    private String description;
}
