/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateInvoiceItemType changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateInvoiceItemType service.
 * Generated from OFBiz service definition; default-entity-name=InvoiceItemType.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateInvoiceItemTypeRequest extends RequestBase {

    private String invoiceItemTypeId;
    private String parentTypeId;
    private String hasTable;
    private String description;
    private String defaultGlAccountId;
}
