/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateAcctgTrans changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateAcctgTrans service.
 * Generated from OFBiz service definition; default-entity-name=AcctgTrans.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateAcctgTransRequest extends RequestBase {

    private String acctgTransId;
    private String acctgTransTypeId;
    private String description;
    private Timestamp transactionDate;
    private String isPosted;
    private Timestamp postedDate;
    private Timestamp scheduledPostingDate;
    private String glJournalId;
    private String glFiscalTypeId;
    private String voucherRef;
    private Timestamp voucherDate;
    private String groupStatusId;
    private String fixedAssetId;
    private String inventoryItemId;
    private String physicalInventoryId;
    private String partyId;
    private String roleTypeId;
    private String invoiceId;
    private String paymentId;
    private String finAccountTransId;
    private String shipmentId;
    private String receiptId;
    private String workEffortId;
    private String theirAcctgTransId;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
}
