/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePartyFixedAssetAssignment changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePartyFixedAssetAssignment service.
 * Generated from OFBiz service definition; default-entity-name=PartyFixedAssetAssignment.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePartyFixedAssetAssignmentRequest extends RequestBase {

    private String partyId;
    private String roleTypeId;
    private String fixedAssetId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Timestamp allocatedDate;
    private String statusId;
    private String comments;
}
