/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePayment changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePayment service.
 * Generated from OFBiz service definition; default-entity-name=Payment.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePaymentRequest extends RequestBase {

    private String paymentId;
    private String paymentTypeId;
    private String paymentMethodTypeId;
    private String paymentMethodId;
    private String paymentGatewayResponseId;
    private String paymentPreferenceId;
    private String partyIdFrom;
    private String partyIdTo;
    private String roleTypeIdTo;
    private String statusId;
    private Timestamp effectiveDate;
    private String paymentRefNum;
    private Double amount;
    private String currencyUomId;
    private String comments;
    private String finAccountTransId;
    private String overrideGlAccountId;
    private Double actualCurrencyAmount;
    private String actualCurrencyUomId;
}
