/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateTaxAuthorityRateProduct changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateTaxAuthorityRateProduct service.
 * Generated from OFBiz service definition; default-entity-name=TaxAuthorityRateProduct.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateTaxAuthorityRateProductRequest extends RequestBase {

    private String taxAuthorityRateSeqId;
    private String taxAuthGeoId;
    private String taxAuthPartyId;
    private String taxAuthorityRateTypeId;
    private String productStoreId;
    private String productCategoryId;
    private String titleTransferEnumId;
    private Double minItemPrice;
    private Double minPurchase;
    private String taxShipping;
    private Double taxPercentage;
    private String taxPromotions;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String description;
    private String isTaxInShippingPrice;
}
