/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePaymentGatewayConfigPayflowPro changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePaymentGatewayConfigPayflowPro service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePaymentGatewayConfigPayflowProRequest extends RequestBase {

    private String paymentGatewayConfigId;
    private String certsPath;
    private String hostAddress;
    private Double hostPort;
    private Double timeout;
    private String proxyAddress;
    private Double proxyPort;
    private String proxyLogon;
    private String proxyPassword;
    private String vendor;
    private String userId;
    private String pwd;
    private String partner;
    private String checkAvs;
    private String checkCvv2;
    private String preAuth;
    private String enableTransmit;
    private String logFileName;
    private Double loggingLevel;
    private Double maxLogFileSize;
    private String stackTraceOn;
    private String redirectUrl;
    private String returnUrl;
    private String cancelReturnUrl;
}
