/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePaymentGroup changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePaymentGroup service.
 * Generated from OFBiz service definition; default-entity-name=PaymentGroup.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePaymentGroupRequest extends RequestBase {

    private String paymentGroupId;
    private String paymentGroupTypeId;
    private String paymentGroupName;
}
