/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateAgreementTerm changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateAgreementTerm service.
 * Generated from OFBiz service definition; default-entity-name=AgreementTerm.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateAgreementTermRequest extends RequestBase {

    private String agreementTermId;
    private String termTypeId;
    private String agreementId;
    private String agreementItemSeqId;
    private String invoiceItemTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double termValue;
    private Double termDays;
    private String textValue;
    private Double minQuantity;
    private Double maxQuantity;
    private String description;
}
