/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePaymentGatewayConfigSagePay changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePaymentGatewayConfigSagePay service.
 * Generated from OFBiz service definition; default-entity-name=PaymentGatewaySagePay.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePaymentGatewayConfigSagePayRequest extends RequestBase {

    private String paymentGatewayConfigId;
    private String vendor;
    private String productionHost;
    private String testingHost;
    private String sagePayMode;
    private String protocolVersion;
    private String authenticationTransType;
    private String authenticationUrl;
    private String authoriseTransType;
    private String authoriseUrl;
    private String releaseTransType;
    private String releaseUrl;
    private String voidUrl;
    private String refundUrl;
}
