/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePaymentGatewayConfigEway changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePaymentGatewayConfigEway service.
 * Generated from OFBiz service definition; default-entity-name=PaymentGatewayEway.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePaymentGatewayConfigEwayRequest extends RequestBase {

    private String paymentGatewayConfigId;
    private String customerId;
    private String refundPwd;
    private String testMode;
    private String enableCvn;
    private String enableBeagle;
}
