/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateTaxAuthorityAssoc changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateTaxAuthorityAssoc service.
 * Generated from OFBiz service definition; default-entity-name=TaxAuthorityAssoc.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateTaxAuthorityAssocRequest extends RequestBase {

    private String taxAuthGeoId;
    private String taxAuthPartyId;
    private String toTaxAuthGeoId;
    private String toTaxAuthPartyId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String taxAuthorityAssocTypeId;
}
