/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateFinAccount changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the updateFinAccount service.
 * Generated from OFBiz service definition; default-entity-name=FinAccount.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateFinAccountResponse extends ResponseBase {

    private String finAccountId;
    private String oldStatusId;
    private String oldReplenishPaymentId;
    private double oldReplenishLevel;
    private String replenishPaymentId;
    private double replenishLevel;
}
