/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateBudgetStatus changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateBudgetStatus service.
 * Generated from OFBiz service definition; default-entity-name=BudgetStatus.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateBudgetStatusRequest extends RequestBase {

    private String budgetId;
    private String statusId;
    private Timestamp statusDate;
    private String comments;
    private String changeByUserLoginId;
}
