/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateCostComponentCalc changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateCostComponentCalc service.
 * Generated from OFBiz service definition; default-entity-name=CostComponentCalc.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateCostComponentCalcRequest extends RequestBase {

    private String costComponentCalcId;
    private String description;
    private String costGlAccountTypeId;
    private String offsettingGlAccountTypeId;
    private Double fixedCost;
    private Double variableCost;
    private Double perMilliSecond;
    private String currencyUomId;
    private String costCustomMethodId;
}
