/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateGlAccount changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateGlAccount service.
 * Generated from OFBiz service definition; default-entity-name=GlAccount.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateGlAccountRequest extends RequestBase {

    private String glAccountId;
    private String glAccountTypeId;
    private String glAccountClassId;
    private String glResourceTypeId;
    private String glXbrlClassId;
    private String parentGlAccountId;
    private String accountCode;
    private String accountName;
    private String description;
    private String productId;
    private String externalId;
}
