/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePaymentGatewayConfigCyberSource changes.
 */
package com.landawn.ofbiz.model.accounting;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePaymentGatewayConfigCyberSource service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePaymentGatewayConfigCyberSourceRequest extends RequestBase {

    private String paymentGatewayConfigId;
    private String merchantId;
    private String apiVersion;
    private String production;
    private String keysDir;
    private String keysFile;
    private String logEnabled;
    private String logDir;
    private String logFile;
    private Double logSize;
    private String merchantDescr;
    private String merchantContact;
    private String autoBill;
    private String enableDav;
    private String fraudScore;
    private String ignoreAvs;
    private String disableBillAvs;
    private String avsDeclineCodes;
}
