/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createSalesForecast changes.
 */
package com.landawn.ofbiz.model.marketing;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createSalesForecast service.
 * Generated from OFBiz service definition; default-entity-name=SalesForecast.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateSalesForecastResponse extends ResponseBase {

    private String salesForecastId;
}
