/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createSalesForecastDetail changes.
 */
package com.landawn.ofbiz.model.marketing;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createSalesForecastDetail service.
 * Generated from OFBiz service definition; default-entity-name=SalesForecastDetail.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateSalesForecastDetailRequest extends RequestBase {

    private String salesForecastId;
    private Double amount;
    private String quantityUomId;
    private Double quantity;
    private String productId;
    private String productCategoryId;
}
