/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteSegmentGroupGeo changes.
 */
package com.landawn.ofbiz.model.marketing;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteSegmentGroupGeo service.
 * Generated from OFBiz service definition; default-entity-name=SegmentGroupGeo.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteSegmentGroupGeoRequest extends RequestBase {

    private String segmentGroupId;
    private String geoId;
}
