/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateContactList changes.
 */
package com.landawn.ofbiz.model.marketing;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateContactList service.
 * Generated from OFBiz service definition; default-entity-name=ContactList.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateContactListRequest extends RequestBase {

    private String contactListId;
    private String contactListTypeId;
    private String contactMechTypeId;
    private String marketingCampaignId;
    private String contactListName;
    private String description;
    private String comments;
    private String isPublic;
    private String singleUse;
    private String ownerPartyId;
    private String verifyEmailFrom;
    private String verifyEmailScreen;
    private String verifyEmailSubject;
    private String verifyEmailWebSiteId;
    private String optOutScreen;
    private String createdByUserLogin;
    private String lastModifiedByUserLogin;
}
