/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateSalesOpportunity changes.
 */
package com.landawn.ofbiz.model.marketing;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateSalesOpportunity service.
 * Generated from OFBiz service definition; default-entity-name=SalesOpportunity.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateSalesOpportunityRequest extends RequestBase {

    private String salesOpportunityId;
    private String opportunityName;
    private String description;
    private String nextStep;
    private Timestamp nextStepDate;
    private Double estimatedAmount;
    private Double estimatedProbability;
    private String currencyUomId;
    private String marketingCampaignId;
    private String dataSourceId;
    private Timestamp estimatedCloseDate;
    private String opportunityStageId;
    private String typeEnumId;
    private String createdByUserLogin;
    private String accountPartyId;
    private String leadPartyId;
}
