/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateContactListParty changes.
 */
package com.landawn.ofbiz.model.marketing;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateContactListParty service.
 * Generated from OFBiz service definition; default-entity-name=ContactListParty.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateContactListPartyRequest extends RequestBase {

    private String contactListId;
    private String partyId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String statusId;
    private String preferredContactMechId;
    private String productStoreId;
    private String optInVerifyCode;
    private String baseLocation;
}
