/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateContactListParty changes.
 */
package com.landawn.ofbiz.model.marketing;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the updateContactListParty service.
 * Generated from OFBiz service definition; default-entity-name=ContactListParty.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateContactListPartyResponse extends ResponseBase {

    private String contactListId;
    private String productStoreId;
}
