/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for addTimesheetToNewInvoice changes.
 */
package com.landawn.ofbiz.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the addTimesheetToNewInvoice service.
 * Generated from OFBiz service definition; default-entity-name=Timesheet.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AddTimesheetToNewInvoiceRequest extends RequestBase {

    private String timesheetId;
    private String partyIdFrom;
    private String partyId;
}
