/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createTimesheetRole changes.
 */
package com.landawn.ofbiz.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createTimesheetRole service.
 * Generated from OFBiz service definition; default-entity-name=TimesheetRole.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateTimesheetRoleResponse extends ResponseBase {

    private String timesheetId;
    private String partyId;
    private String roleTypeId;
}
