/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createWorkEffortContactMech changes.
 */
package com.landawn.ofbiz.model;

import java.sql.Timestamp;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createWorkEffortContactMech service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateWorkEffortContactMechRequest extends RequestBase {

    private Timestamp thruDate;
    private String comments;
    private String partyId;
    private String contactMechId;
    private Timestamp fromDate;
    private String workEffortId;
    private String contactMechTypeId;
    private String infoString;
    private String contactMechPurposeTypeId;
}
