/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createWorkEffortKeywords changes.
 */
package com.landawn.ofbiz.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createWorkEffortKeywords service.
 * Generated from OFBiz service definition; default-entity-name=WorkEffortKeyword.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateWorkEffortKeywordsResponse extends ResponseBase {

    private String workEffortId;
    private Integer keywordsAdded;
}
