/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteWorkEffortKeywords changes.
 */
package com.landawn.ofbiz.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the deleteWorkEffortKeywords service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteWorkEffortKeywordsResponse extends ResponseBase {

    private String workEffortId;
    private Integer deletedRows;
}
