/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteWorkEffort changes.
 */
package com.landawn.ofbiz.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteWorkEffort service.
 * Generated from OFBiz service definition; default-entity-name=WorkEffort.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteWorkEffortRequest extends RequestBase {

    private String workEffortId;
}
