/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteTimeEntry changes.
 */
package com.landawn.ofbiz.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteTimeEntry service.
 * Generated from OFBiz service definition; default-entity-name=TimeEntry.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteTimeEntryRequest extends RequestBase {

    private String timeEntryId;
}
