/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateTimesheet changes.
 */
package com.landawn.ofbiz.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the updateTimesheet service.
 * Generated from OFBiz service definition; default-entity-name=Timesheet.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateTimesheetResponse extends ResponseBase {

    // (no service-specific fields beyond the base envelope)
}
