/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateTimesheet changes.
 */
package com.landawn.ofbiz.model;

import java.sql.Timestamp;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateTimesheet service.
 * Generated from OFBiz service definition; default-entity-name=Timesheet.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateTimesheetRequest extends RequestBase {

    private String timesheetId;
    private String partyId;
    private String clientPartyId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String statusId;
    private String approvedByUserLoginId;
    private String comments;
}
