/*
 * Generated by scripts/gen_workeffort_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateTimeEntry changes.
 */
package com.landawn.ofbiz.model;

import java.sql.Timestamp;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateTimeEntry service.
 * Generated from OFBiz service definition; default-entity-name=TimeEntry.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateTimeEntryRequest extends RequestBase {

    private String timeEntryId;
    private String partyId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String rateTypeId;
    private String workEffortId;
    private String timesheetId;
    private String invoiceId;
    private String invoiceItemSeqId;
    private Double hours;
    private String comments;
}
