/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for entityImportReaders changes.
 */
package com.landawn.ofbiz.model.webtools;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the entityImportReaders service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class EntityImportReadersRequest extends RequestBase {

    private String readers;
    private String overrideDelegator;
    private String overrideGroup;
    private String onlyInserts;
    private String maintainTimeStamps;
    private String createDummyFks;
    private String checkDataOnly;
    private Integer txTimeout;
}
