/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for entityImportDir changes.
 */
package com.landawn.ofbiz.model.webtools;

import com.landawn.ofbiz.model.RequestBase;

import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the entityImportDir service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class EntityImportDirRequest extends RequestBase {

    private String path;
    private String onlyInserts;
    private String maintainTimeStamps;
    private String createDummyFks;
    private String checkDataOnly;
    private String deleteFiles;
    private Integer txTimeout;
    private Long filePause;
    private Map<String, Object> placeholderValues;
}
