/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for saveLabelsToXmlFile changes.
 */
package com.landawn.ofbiz.model.webtools;

import com.landawn.ofbiz.model.RequestBase;

import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the saveLabelsToXmlFile service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SaveLabelsToXmlFileRequest extends RequestBase {

    private String key;
    private String keyComment;
    private String update_label;
    private String fileName;
    private String confirm;
    private String removeLabel;
    private List<String> localeNames;
    private List<Object> localeValues;
    private List<Object> localeComments;
}
