/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createEmplLeaveType changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createEmplLeaveType service.
 * Generated from OFBiz service definition; default-entity-name=EmplLeaveType.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateEmplLeaveTypeRequest extends RequestBase {

    private String leaveTypeId;
    private String parentTypeId;
    private String hasTable;
    private String description;
}
