/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createEmplLeave changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createEmplLeave service.
 * Generated from OFBiz service definition; default-entity-name=EmplLeave.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateEmplLeaveRequest extends RequestBase {

    private String partyId;
    private String leaveTypeId;
    private Timestamp fromDate;
    private String emplLeaveReasonTypeId;
    private Timestamp thruDate;
    private String approverPartyId;
    private String leaveStatus;
    private String description;
}
