/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createJobRequisition changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createJobRequisition service.
 * Generated from OFBiz service definition; default-entity-name=JobRequisition.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateJobRequisitionRequest extends RequestBase {

    private String jobRequisitionId;
    private Double durationMonths;
    private Double age;
    private String gender;
    private Double experienceMonths;
    private Double experienceYears;
    private String qualification;
    private String jobLocation;
    private String skillTypeId;
    private Double noOfResources;
    private String jobPostingTypeEnumId;
    private Date jobRequisitionDate;
    private String examTypeEnumId;
    private Date requiredOnDate;
}
