/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createEmploymentApp changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createEmploymentApp service.
 * Generated from OFBiz service definition; default-entity-name=EmploymentApp.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateEmploymentAppResponse extends ResponseBase {

    private String applicationId;
}
