/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPerformanceNote changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createPerformanceNote service.
 * Generated from OFBiz service definition; default-entity-name=PerformanceNote.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePerformanceNoteRequest extends RequestBase {

    private String partyId;
    private String roleTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Timestamp communicationDate;
    private String comments;
}
