/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPayrollPreference changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createPayrollPreference service.
 * Generated from OFBiz service definition; default-entity-name=PayrollPreference.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePayrollPreferenceRequest extends RequestBase {

    private String partyId;
    private String roleTypeId;
    private String payrollPreferenceSeqId;
    private String deductionTypeId;
    private String paymentMethodTypeId;
    private String periodTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double percentage;
    private Double flatAmount;
    private String routingNumber;
    private String accountNumber;
    private String bankName;
}
