/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createValidResponsibility changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createValidResponsibility service.
 * Generated from OFBiz service definition; default-entity-name=ValidResponsibility.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateValidResponsibilityRequest extends RequestBase {

    private String emplPositionTypeId;
    private String responsibilityTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String comments;
}
