/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteValidResponsibility changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteValidResponsibility service.
 * Generated from OFBiz service definition; default-entity-name=ValidResponsibility.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteValidResponsibilityRequest extends RequestBase {

    private String emplPositionTypeId;
    private String responsibilityTypeId;
    private Timestamp fromDate;
}
