/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for expirePayHistory changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the expirePayHistory service.
 * Generated from OFBiz service definition; default-entity-name=PayHistory.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ExpirePayHistoryRequest extends RequestBase {

    private String roleTypeIdFrom;
    private String roleTypeIdTo;
    private String partyIdFrom;
    private String partyIdTo;
    private Timestamp emplFromDate;
    private Timestamp fromDate;
}
