/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateSalaryStep changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateSalaryStep service.
 * Generated from OFBiz service definition; default-entity-name=SalaryStep.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateSalaryStepRequest extends RequestBase {

    private String salaryStepSeqId;
    private String payGradeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Timestamp dateModified;
    private Double amount;
    private String createdByUserLogin;
    private String lastModifiedByUserLogin;
}
