/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateEmplPositionTypeRate changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateEmplPositionTypeRate service.
 * Generated from OFBiz service definition; default-entity-name=EmplPositionTypeRate.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateEmplPositionTypeRateRequest extends RequestBase {

    private String emplPositionTypeId;
    private String rateTypeId;
    private Timestamp fromDate;
    private String payGradeId;
    private String salaryStepSeqId;
    private Timestamp thruDate;
    private double rateAmount;
    private String rateCurrencyUomId;
    private String periodTypeId;
}
