/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePartySkill changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePartySkill service.
 * Generated from OFBiz service definition; default-entity-name=PartySkill.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePartySkillRequest extends RequestBase {

    private String partyId;
    private String skillTypeId;
    private Double yearsExperience;
    private Double rating;
    private Double skillLevel;
    private Timestamp startedUsingDate;
}
