/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePerfReview changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePerfReview service.
 * Generated from OFBiz service definition; default-entity-name=PerfReview.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePerfReviewRequest extends RequestBase {

    private String employeePartyId;
    private String employeeRoleTypeId;
    private String perfReviewId;
    private String managerPartyId;
    private String managerRoleTypeId;
    private String paymentId;
    private String emplPositionId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String comments;
}
