/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePartyBenefit changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePartyBenefit service.
 * Generated from OFBiz service definition; default-entity-name=PartyBenefit.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePartyBenefitRequest extends RequestBase {

    private String roleTypeIdFrom;
    private String roleTypeIdTo;
    private String partyIdFrom;
    private String partyIdTo;
    private String benefitTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String periodTypeId;
    private Double cost;
    private Double actualEmployerPaidPercent;
    private Double availableTime;
}
