/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateJobInterview changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateJobInterview service.
 * Generated from OFBiz service definition; default-entity-name=JobInterview.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateJobInterviewRequest extends RequestBase {

    private String jobInterviewId;
    private String jobIntervieweePartyId;
    private String jobRequisitionId;
    private String jobInterviewerPartyId;
    private String jobInterviewTypeId;
    private String gradeSecuredEnumId;
    private String jobInterviewResult;
    private Date jobInterviewDate;
}
