/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateEmplPositionReportingStruct changes.
 */
package com.landawn.ofbiz.model.humanres;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateEmplPositionReportingStruct service.
 * Generated from OFBiz service definition; default-entity-name=EmplPositionReportingStruct.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateEmplPositionReportingStructRequest extends RequestBase {

    private String emplPositionIdReportingTo;
    private String emplPositionIdManagedBy;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String comments;
    private String primaryFlag;
}
