/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for addFacilityGroupToGroup changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the addFacilityGroupToGroup service.
 * Generated from OFBiz service definition; default-entity-name=FacilityGroupRollup.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AddFacilityGroupToGroupRequest extends RequestBase {

    private String facilityGroupId;
    private String parentFacilityGroupId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double sequenceNum;
}
