/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for addImageForProductPromo changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the addImageForProductPromo service.
 * Generated from OFBiz service definition; default-entity-name=ProductPromoContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AddImageForProductPromoRequest extends RequestBase {

    private String productPromoId;
    private String contentId;
    private String productPromoContentTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
}
