/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for addProductToCategories changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the addProductToCategories service.
 * Generated from OFBiz service definition; default-entity-name=ProductCategoryMember.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AddProductToCategoriesRequest extends RequestBase {

    private String productId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String comments;
    private Double sequenceNum;
    private Double quantity;
    private String categories;
}
