/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for completePack changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the completePack service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CompletePackRequest extends RequestBase {

    private Object packingSession;
    private String orderId;
    private String invoiceId;
    private String shipmentId;
    private String handlingInstructions;
    private String pickerPartyId;
    private double additionalShippingCharge;
    private Boolean forceComplete;
    private Map<String, Object> packageWeights;
    private String dimensionUomId;
    private String weightUomId;
    private Map<String, Object> boxTypes;
}
