/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for completePackage changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the completePackage service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CompletePackageRequest extends RequestBase {

    private Object weightPackageSession;
    private String orderId;
    private String invoiceId;
    private String facilityId;
    private String dimensionUomId;
    private String weightUomId;
    private double estimatedShippingCost;
    private double newEstimatedShippingCost;
    private String shipmentId;
}
