/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for copyToProductVariants changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the copyToProductVariants service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CopyToProductVariantsRequest extends RequestBase {

    private String virtualProductId;
    private String removeBefore;
    private String duplicateProduct;
    private String duplicatePrices;
    private String duplicateIDs;
    private String duplicateContent;
    private String duplicateCategoryMembers;
    private String duplicateAttributes;
    private String duplicateFacilities;
    private String duplicateLocations;
}
