/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createShipmentPackageRouteSeg changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createShipmentPackageRouteSeg service.
 * Generated from OFBiz service definition; default-entity-name=ShipmentPackageRouteSeg.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateShipmentPackageRouteSegRequest extends RequestBase {

    private String shipmentId;
    private String shipmentPackageSeqId;
    private String shipmentRouteSegmentId;
    private String trackingCode;
    private String boxNumber;
    private byte[] labelImage;
    private byte[] labelIntlSignImage;
    private String labelHtml;
    private String labelPrinted;
    private byte[] internationalInvoice;
    private Double packageTransportCost;
    private Double packageServiceCost;
    private Double packageOtherCost;
    private Double codAmount;
    private Double insuredAmount;
    private String currencyUomId;
}
