/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createShipment changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createShipment service.
 * Generated from OFBiz service definition; default-entity-name=Shipment.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateShipmentRequest extends RequestBase {

    private String shipmentId;
    private String shipmentTypeId;
    private String statusId;
    private String primaryOrderId;
    private String primaryReturnId;
    private String primaryShipGroupSeqId;
    private String picklistBinId;
    private Timestamp estimatedReadyDate;
    private Timestamp estimatedShipDate;
    private String estimatedShipWorkEffId;
    private Timestamp estimatedArrivalDate;
    private String estimatedArrivalWorkEffId;
    private Timestamp latestCancelDate;
    private Double estimatedShipCost;
    private String currencyUomId;
    private String handlingInstructions;
    private String originFacilityId;
    private String destinationFacilityId;
    private String originContactMechId;
    private String originTelecomNumberId;
    private String destinationContactMechId;
    private String destinationTelecomNumberId;
    private String partyIdTo;
    private String partyIdFrom;
    private Double additionalShippingCharge;
    private String addtlShippingChargeDesc;
}
