/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductStoreFinActSetting changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductStoreFinActSetting service.
 * Generated from OFBiz service definition; default-entity-name=ProductStoreFinActSetting.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductStoreFinActSettingRequest extends RequestBase {

    private String productStoreId;
    private String finAccountTypeId;
    private String requirePinCode;
    private String validateGcfinAcct;
    private Double accountCodeLength;
    private Double pinCodeLength;
    private Double accountValidDays;
    private Double authValidDays;
    private String purchaseSurveyId;
    private String purchSurveySendTo;
    private String purchSurveyCopyMe;
    private String allowAuthToNegative;
    private Double minBalance;
    private Double replenishThreshold;
    private String replenishMethodEnumId;
}
