/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductStoreSurveyAppl changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductStoreSurveyAppl service.
 * Generated from OFBiz service definition; default-entity-name=ProductStoreSurveyAppl.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductStoreSurveyApplRequest extends RequestBase {

    private String productStoreId;
    private String surveyApplTypeId;
    private String groupName;
    private String surveyId;
    private String productId;
    private String productCategoryId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String surveyTemplate;
    private String resultTemplate;
    private Double sequenceNum;
}
