/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductFeatureIactn changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductFeatureIactn service.
 * Generated from OFBiz service definition; default-entity-name=ProductFeatureIactn.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductFeatureIactnRequest extends RequestBase {

    private String productFeatureId;
    private String productFeatureIdTo;
    private String productFeatureIactnTypeId;
    private String productId;
}
