/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createShipmentPackageContent changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createShipmentPackageContent service.
 * Generated from OFBiz service definition; default-entity-name=ShipmentPackageContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateShipmentPackageContentRequest extends RequestBase {

    private String shipmentId;
    private String shipmentItemSeqId;
    private Double quantity;
    private String subProductId;
    private Double subProductQuantity;
    private String shipmentPackageSeqId;
}
