/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCostComponent changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createCostComponent service.
 * Generated from OFBiz service definition; default-entity-name=CostComponent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCostComponentRequest extends RequestBase {

    private String costComponentTypeId;
    private String productId;
    private String productFeatureId;
    private String partyId;
    private String geoId;
    private String workEffortId;
    private String fixedAssetId;
    private String costComponentCalcId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double cost;
    private String costUomId;
}
