/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductContent changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductContent service.
 * Generated from OFBiz service definition; default-entity-name=ProductContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductContentRequest extends RequestBase {

    private String productId;
    private String contentId;
    private String productContentTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Timestamp purchaseFromDate;
    private Timestamp purchaseThruDate;
    private Double useCountLimit;
    private Double useTime;
    private String useTimeUomId;
    private String useRoleTypeId;
    private Double sequenceNum;
    private String contentTypeId;
    private String ownerContentId;
    private String decoratorContentId;
    private String instanceOfContentId;
    private String dataResourceId;
    private String templateDataResourceId;
    private String dataSourceId;
    private String statusId;
    private String privilegeEnumId;
    private String serviceName;
    private String customMethodId;
    private String contentName;
    private String description;
    private String localeString;
    private String mimeTypeId;
    private String characterSetId;
    private Double childLeafCount;
    private Double childBranchCount;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
}
