/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductPromoCond changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductPromoCond service.
 * Generated from OFBiz service definition; default-entity-name=ProductPromoCond.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductPromoCondRequest extends RequestBase {

    private String productPromoId;
    private String productPromoRuleId;
    private String customMethodId;
    private String inputParamEnumId;
    private String operatorEnumId;
    private String condValue;
    private String otherValue;
    private String carrierShipmentMethod;
}
