/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProdCatalog changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProdCatalog service.
 * Generated from OFBiz service definition; default-entity-name=ProdCatalog.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProdCatalogRequest extends RequestBase {

    private String prodCatalogId;
    private String catalogName;
    private String useQuickAdd;
    private String styleSheet;
    private String headerLogo;
    private String contentPathPrefix;
    private String templatePathPrefix;
    private String viewAllowPermReqd;
    private String purchaseAllowPermReqd;
}
