/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductFacilityLocation changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductFacilityLocation service.
 * Generated from OFBiz service definition; default-entity-name=ProductFacilityLocation.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductFacilityLocationRequest extends RequestBase {

    private String productId;
    private String facilityId;
    private String locationSeqId;
    private Double minimumStock;
    private Double moveQuantity;
}
