/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductPromo changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductPromo service.
 * Generated from OFBiz service definition; default-entity-name=ProductPromo.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductPromoRequest extends RequestBase {

    private String promoName;
    private String promoText;
    private String userEntered;
    private String showToCustomer;
    private String requireCode;
    private Double useLimitPerOrder;
    private Double useLimitPerCustomer;
    private Double useLimitPerPromotion;
    private Double billbackFactor;
    private String overrideOrgPartyId;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
}
