/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createInventoryTransfer changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createInventoryTransfer service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateInventoryTransferRequest extends RequestBase {

    private String inventoryItemId;
    private String statusId;
    private String facilityId;
    private String locationSeqId;
    private String containerId;
    private String facilityIdTo;
    private String locationSeqIdTo;
    private String containerIdTo;
    private String itemIssuanceId;
    private Timestamp sendDate;
    private Timestamp receiveDate;
    private String comments;
    private double xferQty;
}
