/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductStore changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createProductStore service.
 * Generated from OFBiz service definition; default-entity-name=ProductStore.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductStoreRequest extends RequestBase {

    private String primaryStoreGroupId;
    private String storeName;
    private String companyName;
    private String title;
    private String subtitle;
    private String payToPartyId;
    private Double daysToCancelNonPay;
    private String manualAuthIsCapture;
    private String prorateShipping;
    private String prorateTaxes;
    private String viewCartOnAdd;
    private String autoSaveCart;
    private String autoApproveReviews;
    private String isDemoStore;
    private String isImmediatelyFulfilled;
    private String inventoryFacilityId;
    private String oneInventoryFacility;
    private String checkInventory;
    private String reserveInventory;
    private String reserveOrderEnumId;
    private String requireInventory;
    private String balanceResOnOrderCreation;
    private String requirementMethodEnumId;
    private String orderNumberPrefix;
    private String defaultLocaleString;
    private String defaultCurrencyUomId;
    private String defaultTimeZoneString;
    private String defaultSalesChannelEnumId;
    private String allowPassword;
    private String defaultPassword;
    private String explodeOrderItems;
    private String checkGcBalance;
    private String retryFailedAuths;
    private String headerApprovedStatus;
    private String itemApprovedStatus;
    private String digitalItemApprovedStatus;
    private String headerDeclinedStatus;
    private String itemDeclinedStatus;
    private String headerCancelStatus;
    private String itemCancelStatus;
    private String authDeclinedMessage;
    private String authFraudMessage;
    private String authErrorMessage;
    private String visualThemeId;
    private String storeCreditAccountEnumId;
    private String usePrimaryEmailUsername;
    private String requireCustomerRole;
    private String autoInvoiceDigitalItems;
    private String reqShipAddrForDigItems;
    private String showCheckoutGiftOptions;
    private String selectPaymentTypePerItem;
    private String showPricesWithVatTax;
    private String showTaxIsExempt;
    private String vatTaxAuthGeoId;
    private String vatTaxAuthPartyId;
    private String enableAutoSuggestionList;
    private String enableDigProdUpload;
    private String prodSearchExcludeVariants;
    private String digProdUploadCategoryId;
    private String autoOrderCcTryExp;
    private String autoOrderCcTryOtherCards;
    private String autoOrderCcTryLaterNsf;
    private Double autoOrderCcTryLaterMax;
    private Double storeCreditValidDays;
    private String autoApproveInvoice;
    private String autoApproveOrder;
    private String shipIfCaptureFails;
    private String setOwnerUponIssuance;
    private String reqReturnInventoryReceive;
    private String addToCartRemoveIncompat;
    private String addToCartReplaceUpsell;
    private String splitPayPrefPerShpGrp;
    private String managedByLot;
    private String showOutOfStockProducts;
    private String orderDecimalQuantity;
    private String allowComment;
    private String allocateInventory;
}
