/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createShipmentEstimate changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createShipmentEstimate service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateShipmentEstimateRequest extends RequestBase {

    private String productStoreShipMethId;
    private String toGeo;
    private String fromGeo;
    private String partyId;
    private String roleTypeId;
    private double flatPercent;
    private double flatPrice;
    private double flatItemPrice;
    private double shippingPricePercent;
    private String productFeatureGroupId;
    private double featurePercent;
    private double featurePrice;
    private double oversizeUnit;
    private double oversizePrice;
    private String weightBreakId;
    private double wmin;
    private double wmax;
    private double wprice;
    private String wuom;
    private String quantityBreakId;
    private double qmin;
    private double qmax;
    private double qprice;
    private String quom;
    private String priceBreakId;
    private double pmin;
    private double pmax;
    private double pprice;
    private String puom;
}
