/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createRelatedUrlContentForCategory changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createRelatedUrlContentForCategory service.
 * Generated from OFBiz service definition; default-entity-name=ProductCategoryContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateRelatedUrlContentForCategoryRequest extends RequestBase {

    private String productCategoryId;
    private String contentId;
    private String prodCatContentTypeId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Timestamp purchaseFromDate;
    private Timestamp purchaseThruDate;
    private Double useCountLimit;
    private Double useDaysLimit;
    private String title;
    private String description;
    private String url;
    private String localeString;
}
