/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createShipmentPackageContent changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createShipmentPackageContent service.
 * Generated from OFBiz service definition; default-entity-name=ShipmentPackageContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateShipmentPackageContentResponse extends ResponseBase {

    private String shipmentPackageSeqId;
}
