/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createProductPromoAction changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createProductPromoAction service.
 * Generated from OFBiz service definition; default-entity-name=ProductPromoAction.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateProductPromoActionResponse extends ResponseBase {

    private String productPromoActionSeqId;
}
