/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteProductStoreVendorShipment changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteProductStoreVendorShipment service.
 * Generated from OFBiz service definition; default-entity-name=ProductStoreVendorShipment.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteProductStoreVendorShipmentRequest extends RequestBase {

    private String productStoreId;
    private String vendorPartyId;
    private String shipmentMethodTypeId;
    private String carrierPartyId;
}
