/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteProductCategoryLink changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteProductCategoryLink service.
 * Generated from OFBiz service definition; default-entity-name=ProductCategoryLink.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteProductCategoryLinkRequest extends RequestBase {

    private String productCategoryId;
    private String linkSeqId;
    private Timestamp fromDate;
}
