/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteProductPromoCodeContactMech changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteProductPromoCodeContactMech service.
 * Generated from OFBiz service definition; default-entity-name=ProdPromoCodeContactMech.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteProductPromoCodeContactMechRequest extends RequestBase {

    private String productPromoCodeId;
    private String contactMechId;
}
