/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteProductStorePaymentSetting changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteProductStorePaymentSetting service.
 * Generated from OFBiz service definition; default-entity-name=ProductStorePaymentSetting.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteProductStorePaymentSettingRequest extends RequestBase {

    private String productStoreId;
    private String paymentMethodTypeId;
    private String paymentServiceTypeEnumId;
}
