/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for duplicateProduct changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the duplicateProduct service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DuplicateProductRequest extends RequestBase {

    private String productId;
    private String oldProductId;
    private String newInternalName;
    private String newProductName;
    private String newDescription;
    private String newLongDescription;
    private String duplicatePrices;
    private String duplicateIDs;
    private String duplicateContent;
    private String duplicateCategoryMembers;
    private String duplicateAssocs;
    private String duplicateAttributes;
    private String duplicateFeatureAppls;
    private String duplicateInventoryItems;
    private String removePrices;
    private String removeIDs;
    private String removeContent;
    private String removeCategoryMembers;
    private String removeAssocs;
    private String removeAttributes;
    private String removeFeatureAppls;
    private String removeInventoryItems;
}
