/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for duplicateProductCategory changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the duplicateProductCategory service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DuplicateProductCategoryRequest extends RequestBase {

    private String productCategoryId;
    private String oldProductCategoryId;
    private String duplicateContent;
    private String duplicateParentRollup;
    private String duplicateChildRollup;
    private String duplicateMembers;
    private String duplicateCatalogs;
    private String duplicateFeatureCategories;
    private String duplicateFeatureGroups;
    private String duplicateAttributes;
    private String duplicateRoles;
}
