/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for issueOrderItemShipGrpInvResToShipment changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the issueOrderItemShipGrpInvResToShipment service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class IssueOrderItemShipGrpInvResToShipmentResponse extends ResponseBase {

    private String shipmentItemSeqId;
    private String itemIssuanceId;
}
