/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for issueOrderItemShipGrpInvResToShipment changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the issueOrderItemShipGrpInvResToShipment service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class IssueOrderItemShipGrpInvResToShipmentRequest extends RequestBase {

    private String shipmentId;
    private String orderId;
    private String shipGroupSeqId;
    private String orderItemSeqId;
    private String inventoryItemId;
    private double quantity;
    private Timestamp eventDate;
}
