/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for multipleUploadProductImages changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the multipleUploadProductImages service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class MultipleUploadProductImagesRequest extends RequestBase {

    private String productId;
    private String imageResize;
    private byte[] additionalImageOne;
    private String _additionalImageOne_fileName;
    private String _additionalImageOne_contentType;
    private byte[] additionalImageTwo;
    private String _additionalImageTwo_fileName;
    private String _additionalImageTwo_contentType;
    private byte[] additionalImageThree;
    private String _additionalImageThree_fileName;
    private String _additionalImageThree_contentType;
    private byte[] additionalImageFour;
    private String _additionalImageFour_fileName;
    private String _additionalImageFour_contentType;
    private byte[] additionalImageFive;
    private String _additionalImageFive_fileName;
    private String _additionalImageFive_contentType;
    private byte[] additionalImageSix;
    private String _additionalImageSix_fileName;
    private String _additionalImageSix_contentType;
    private byte[] additionalImageSeven;
    private String _additionalImageSeven_fileName;
    private String _additionalImageSeven_contentType;
    private byte[] additionalImageEight;
    private String _additionalImageEight_fileName;
    private String _additionalImageEight_contentType;
    private byte[] additionalImageNine;
    private String _additionalImageNine_fileName;
    private String _additionalImageNine_contentType;
    private byte[] additionalImageTen;
    private String _additionalImageTen_fileName;
    private String _additionalImageTen_contentType;
}
