/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for packSingleItem changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the packSingleItem service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class PackSingleItemRequest extends RequestBase {

    private Object packingSession;
    private String productId;
    private String orderId;
    private String shipGroupSeqId;
    private double quantity;
    private Integer packageSeq;
    private String pickerPartyId;
    private String handlingInstructions;
}
