/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for printPickSheets changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.ResponseBase;

import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the printPickSheets service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class PrintPickSheetsResponse extends ResponseBase {

    private List<String> pickMoveInfoList;
}
