/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeSupplierProduct changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeSupplierProduct service.
 * Generated from OFBiz service definition; default-entity-name=SupplierProduct.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveSupplierProductRequest extends RequestBase {

    private String productId;
    private String partyId;
    private Timestamp availableFromDate;
    private Double minimumOrderQuantity;
    private String currencyUomId;
}
