/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeProductCategoryFromProdCatalog changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeProductCategoryFromProdCatalog service.
 * Generated from OFBiz service definition; default-entity-name=ProdCatalogCategory.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveProductCategoryFromProdCatalogRequest extends RequestBase {

    private String prodCatalogId;
    private String productCategoryId;
    private String prodCatalogCategoryTypeId;
    private Timestamp fromDate;
}
