/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for setPackageInfo changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the setPackageInfo service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SetPackageInfoRequest extends RequestBase {

    private Object weightPackageSession;
    private String orderId;
    private double packageWeight;
    private double packageLength;
    private double packageWidth;
    private double packageHeight;
    private String shipmentBoxTypeId;
}
