/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductConfig changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductConfig service.
 * Generated from OFBiz service definition; default-entity-name=ProductConfig.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductConfigRequest extends RequestBase {

    private String productId;
    private String configItemId;
    private Double sequenceNum;
    private Timestamp fromDate;
    private String description;
    private String longDescription;
    private String configTypeId;
    private String defaultConfigOptionId;
    private Timestamp thruDate;
    private String isMandatory;
}
