/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductConfigOption changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductConfigOption service.
 * Generated from OFBiz service definition; default-entity-name=ProductConfigOption.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductConfigOptionRequest extends RequestBase {

    private String configItemId;
    private String configOptionId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String configOptionName;
    private String description;
    private Double sequenceNum;
}
