/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductCategoryAttribute changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductCategoryAttribute service.
 * Generated from OFBiz service definition; default-entity-name=ProductCategoryAttribute.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductCategoryAttributeRequest extends RequestBase {

    private String productCategoryId;
    private String attrName;
    private String attrValue;
    private String attrDescription;
}
