/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductPrice changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductPrice service.
 * Generated from OFBiz service definition; default-entity-name=ProductPrice.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductPriceRequest extends RequestBase {

    private String productId;
    private String productPriceTypeId;
    private String productPricePurposeId;
    private String currencyUomId;
    private String productStoreGroupId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double price;
    private String termUomId;
    private String customPriceCalcService;
    private Double taxPercentage;
    private String taxAuthPartyId;
    private String taxAuthGeoId;
    private String taxInPrice;
}
