/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductFeatureCatGrpAppl changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductFeatureCatGrpAppl service.
 * Generated from OFBiz service definition; default-entity-name=ProductFeatureCatGrpAppl.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductFeatureCatGrpApplRequest extends RequestBase {

    private String productCategoryId;
    private String productFeatureGroupId;
    private Timestamp fromDate;
    private Timestamp thruDate;
}
