/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateShipmentTimeEstimate changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateShipmentTimeEstimate service.
 * Generated from OFBiz service definition; default-entity-name=ShipmentTimeEstimate.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateShipmentTimeEstimateRequest extends RequestBase {

    private String shipmentMethodTypeId;
    private String partyId;
    private String roleTypeId;
    private String geoIdTo;
    private String geoIdFrom;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double leadTime;
    private String leadTimeUomId;
    private Double sequenceNumber;
}
