/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductStoreShipMeth changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductStoreShipMeth service.
 * Generated from OFBiz service definition; default-entity-name=ProductStoreShipmentMeth.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductStoreShipMethRequest extends RequestBase {

    private String productStoreShipMethId;
    private String productStoreId;
    private String shipmentMethodTypeId;
    private String partyId;
    private String roleTypeId;
    private String companyPartyId;
    private Double minWeight;
    private Double maxWeight;
    private Double minSize;
    private Double maxSize;
    private Double minTotal;
    private Double maxTotal;
    private String allowUspsAddr;
    private String requireUspsAddr;
    private String allowCompanyAddr;
    private String requireCompanyAddr;
    private String includeNoChargeItems;
    private String includeFeatureGroup;
    private String excludeFeatureGroup;
    private String includeGeoId;
    private String excludeGeoId;
    private String serviceName;
    private String configProps;
    private String shipmentCustomMethodId;
    private String shipmentGatewayConfigId;
    private Double sequenceNumber;
    private Double allowancePercent;
    private Double minimumPrice;
}
