/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductFacility changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductFacility service.
 * Generated from OFBiz service definition; default-entity-name=ProductFacility.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductFacilityRequest extends RequestBase {

    private String productId;
    private String facilityId;
    private Double minimumStock;
    private Double reorderQuantity;
    private Double daysToShip;
    private String replenishMethodEnumId;
    private Double lastInventoryCount;
    private String requirementMethodEnumId;
}
