/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductStoreGroup changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductStoreGroup service.
 * Generated from OFBiz service definition; default-entity-name=ProductStoreGroup.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductStoreGroupRequest extends RequestBase {

    private String productStoreGroupId;
    private String productStoreGroupTypeId;
    private String primaryParentGroupId;
    private String productStoreGroupName;
    private String description;
}
