/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateFeaturePrice changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateFeaturePrice service.
 * Generated from OFBiz service definition; default-entity-name=ProductFeaturePrice.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateFeaturePriceRequest extends RequestBase {

    private String productFeatureId;
    private String productPriceTypeId;
    private String currencyUomId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double price;
}
