/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductStoreGroupRollup changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductStoreGroupRollup service.
 * Generated from OFBiz service definition; default-entity-name=ProductStoreGroupRollup.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductStoreGroupRollupRequest extends RequestBase {

    private String productStoreGroupId;
    private String parentGroupId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double sequenceNum;
}
