/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductStoreKeywordOvrd changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductStoreKeywordOvrd service.
 * Generated from OFBiz service definition; default-entity-name=ProductStoreKeywordOvrd.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductStoreKeywordOvrdRequest extends RequestBase {

    private String productStoreId;
    private String keyword;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String target;
    private String targetTypeEnumId;
}
