/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductStorePaymentSetting changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductStorePaymentSetting service.
 * Generated from OFBiz service definition; default-entity-name=ProductStorePaymentSetting.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductStorePaymentSettingRequest extends RequestBase {

    private String productStoreId;
    private String paymentMethodTypeId;
    private String paymentServiceTypeEnumId;
    private String paymentService;
    private String paymentCustomMethodId;
    private String paymentGatewayConfigId;
    private String paymentPropertiesPath;
    private String applyToAllProducts;
}
