/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateShipmentPackage changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateShipmentPackage service.
 * Generated from OFBiz service definition; default-entity-name=ShipmentPackage.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateShipmentPackageRequest extends RequestBase {

    private String shipmentId;
    private String shipmentPackageSeqId;
    private String shipmentBoxTypeId;
    private Timestamp dateCreated;
    private Double boxLength;
    private Double boxHeight;
    private Double boxWidth;
    private String dimensionUomId;
    private Double weight;
    private String weightUomId;
    private Double insuredValue;
}
