/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductCostComponentCalc changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductCostComponentCalc service.
 * Generated from OFBiz service definition; default-entity-name=ProductCostComponentCalc.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductCostComponentCalcRequest extends RequestBase {

    private String productId;
    private String costComponentTypeId;
    private Timestamp fromDate;
    private String costComponentCalcId;
    private Double sequenceNum;
    private Timestamp thruDate;
}
