/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateInventoryItemLabelAppl changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateInventoryItemLabelAppl service.
 * Generated from OFBiz service definition; default-entity-name=InventoryItemLabelAppl.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateInventoryItemLabelApplRequest extends RequestBase {

    private String inventoryItemId;
    private String inventoryItemLabelTypeId;
    private String inventoryItemLabelId;
    private Double sequenceNum;
}
