/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductQuickAdminName changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductQuickAdminName service.
 * Generated from OFBiz service definition; default-entity-name=Product.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductQuickAdminNameRequest extends RequestBase {

    private String productTypeId;
    private String primaryProductCategoryId;
    private String facilityId;
    private Timestamp introductionDate;
    private Timestamp releaseDate;
    private Timestamp supportDiscontinuationDate;
    private Timestamp salesDiscontinuationDate;
    private String salesDiscWhenNotAvail;
    private String internalName;
    private String brandName;
    private String comments;
    private String productName;
    private String description;
    private String longDescription;
    private String priceDetailText;
    private String smallImageUrl;
    private String mediumImageUrl;
    private String largeImageUrl;
    private String detailImageUrl;
    private String originalImageUrl;
    private String detailScreen;
    private String inventoryMessage;
    private String inventoryItemTypeId;
    private String requireInventory;
    private String quantityUomId;
    private Double quantityIncluded;
    private Double piecesIncluded;
    private String requireAmount;
    private Double fixedAmount;
    private String amountUomTypeId;
    private String weightUomId;
    private Double shippingWeight;
    private Double productWeight;
    private String heightUomId;
    private Double productHeight;
    private Double shippingHeight;
    private String widthUomId;
    private Double productWidth;
    private Double shippingWidth;
    private String depthUomId;
    private Double productDepth;
    private Double shippingDepth;
    private String diameterUomId;
    private Double productDiameter;
    private Double productRating;
    private String ratingTypeEnum;
    private String returnable;
    private String taxable;
    private String chargeShipping;
    private String autoCreateKeywords;
    private String includeInPromotions;
    private String isVirtual;
    private String isVariant;
    private String virtualVariantMethodEnum;
    private String originGeoId;
    private String requirementMethodEnumId;
    private Double billOfMaterialLevel;
    private Double reservMaxPersons;
    private Double reserv2ndPpperc;
    private Double reservNthPpperc;
    private String configId;
    private String inShippingBox;
    private String defaultShipmentBoxTypeId;
    private String lotIdFilledIn;
    private String orderDecimalQuantity;
    private String productId;
}
