/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateProductPriceCond changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateProductPriceCond service.
 * Generated from OFBiz service definition; default-entity-name=ProductPriceCond.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateProductPriceCondRequest extends RequestBase {

    private String productPriceRuleId;
    private String productPriceCondSeqId;
    private String inputParamEnumId;
    private String operatorEnumId;
    private String condValue;
    private String condValueInput;
}
