/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateSimpleTextContentForProductConfigItem changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateSimpleTextContentForProductConfigItem service.
 * Generated from OFBiz service definition; default-entity-name=ProdConfItemContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateSimpleTextContentForProductConfigItemRequest extends RequestBase {

    // (no service-specific fields beyond the base envelope)
}
