/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateFacilityPostalAddress changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateFacilityPostalAddress service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateFacilityPostalAddressRequest extends RequestBase {

    private String facilityId;
    private String contactMechId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String extension;
    private String comments;
    private String toName;
    private String attnName;
    private String address1;
    private String address2;
    private Double houseNumber;
    private String houseNumberExt;
    private String directions;
    private String city;
    private String cityGeoId;
    private String postalCode;
    private String postalCodeExt;
    private String countryGeoId;
    private String stateProvinceGeoId;
    private String countyGeoId;
    private String municipalityGeoId;
    private String postalCodeGeoId;
    private String geoPointId;
    private String latitude;
    private String longitude;
}
