/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateFacility changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateFacility service.
 * Generated from OFBiz service definition; default-entity-name=Facility.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateFacilityRequest extends RequestBase {

    private String facilityId;
    private String facilityTypeId;
    private String parentFacilityId;
    private String ownerPartyId;
    private String defaultInventoryItemTypeId;
    private String facilityName;
    private String primaryFacilityGroupId;
    private Double facilitySize;
    private String facilitySizeUomId;
    private String productStoreId;
    private Double defaultDaysToShip;
    private Timestamp openedDate;
    private Timestamp closedDate;
    private String description;
    private String defaultDimensionUomId;
    private String defaultWeightUomId;
    private String geoPointId;
    private Double facilityLevel;
    private String autoReservePrun;
    private String allowInventoryReallocation;
    private String reconcilePrunBackorders;
}
