/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for uploadProductAdditionalViewImages changes.
 */
package com.landawn.ofbiz.model.product;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the uploadProductAdditionalViewImages service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UploadProductAdditionalViewImagesRequest extends RequestBase {

    private String productId;
    private byte[] additionalImageOne;
    private String _additionalImageOne_fileName;
    private String _additionalImageOne_contentType;
    private byte[] additionalImageTwo;
    private String _additionalImageTwo_fileName;
    private String _additionalImageTwo_contentType;
    private byte[] additionalImageThree;
    private String _additionalImageThree_fileName;
    private String _additionalImageThree_contentType;
    private byte[] additionalImageFour;
    private String _additionalImageFour_fileName;
    private String _additionalImageFour_contentType;
}
