/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPartyRelationshipType changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createPartyRelationshipType service.
 * Generated from OFBiz service definition; default-entity-name=PartyRelationshipType.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePartyRelationshipTypeRequest extends RequestBase {

    private String partyRelationshipTypeId;
    private String parentTypeId;
    private String hasTable;
    private String partyRelationshipName;
    private String description;
    private String roleTypeIdValidFrom;
    private String roleTypeIdValidTo;
}
