/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPartyEmailAddress changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createPartyEmailAddress service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePartyEmailAddressRequest extends RequestBase {

    private String contactMechTypeId;
    private String infoString;
    private String partyId;
    private String contactMechId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String roleTypeId;
    private String allowSolicitation;
    private String extension;
    private String verified;
    private String comments;
    private Double yearsWithContactMech;
    private Double monthsWithContactMech;
    private String contactMechPurposeTypeId;
    private String emailAddress;
}
