/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createCommunicationEvent changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createCommunicationEvent service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateCommunicationEventRequest extends RequestBase {

    private String communicationEventTypeId;
    private String origCommEventId;
    private String parentCommEventId;
    private String statusId;
    private String contactMechTypeId;
    private String contactMechIdFrom;
    private String contactMechIdTo;
    private String roleTypeIdFrom;
    private String roleTypeIdTo;
    private String partyIdFrom;
    private String partyIdTo;
    private Timestamp entryDate;
    private Timestamp datetimeStarted;
    private Timestamp datetimeEnded;
    private String subject;
    private String contentMimeTypeId;
    private String content;
    private String note;
    private String reasonEnumId;
    private String contactListId;
    private String headerString;
    private String fromString;
    private String toString;
    private String ccString;
    private String bccString;
    private String messageId;
    private String communicationEventId;
    private String productId;
    private String orderId;
    private String returnId;
    private String custRequestId;
    private String action;
}
