/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createPartyGroup changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createPartyGroup service.
 * Generated from OFBiz service definition; default-entity-name=PartyGroup.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreatePartyGroupResponse extends ResponseBase {

    private String partyId;
}
