/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deletePartyIdentification changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deletePartyIdentification service.
 * Generated from OFBiz service definition; default-entity-name=PartyIdentification.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeletePartyIdentificationRequest extends RequestBase {

    private String partyId;
    private String partyIdentificationTypeId;
}
