/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeCommunicationEventPurpose changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeCommunicationEventPurpose service.
 * Generated from OFBiz service definition; default-entity-name=CommunicationEventPurpose.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveCommunicationEventPurposeRequest extends RequestBase {

    private String communicationEventPrpTypId;
    private String communicationEventId;
}
