/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePartyGroup changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePartyGroup service.
 * Generated from OFBiz service definition; default-entity-name=PartyGroup.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePartyGroupRequest extends RequestBase {

    private String partyId;
    private String groupName;
    private String groupNameLocal;
    private String officeSiteName;
    private Double annualRevenue;
    private Double numEmployees;
    private String tickerSymbol;
    private String comments;
    private String logoImageUrl;
    private String description;
    private String partyTypeId;
    private String preferredCurrencyUomId;
    private String externalId;
    private String statusId;
}
