/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateVendor changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateVendor service.
 * Generated from OFBiz service definition; default-entity-name=Vendor.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateVendorRequest extends RequestBase {

    private String partyId;
    private String manifestCompanyName;
    private String manifestCompanyTitle;
    private String manifestLogoUrl;
    private String manifestPolicies;
}
