/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePerson changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePerson service.
 * Generated from OFBiz service definition; default-entity-name=Person.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePersonRequest extends RequestBase {

    private String partyId;
    private String salutation;
    private String firstName;
    private String middleName;
    private String lastName;
    private String personalTitle;
    private String suffix;
    private String nickname;
    private String firstNameLocal;
    private String middleNameLocal;
    private String lastNameLocal;
    private String otherLocal;
    private String memberId;
    private String gender;
    private Date birthDate;
    private Date deceasedDate;
    private Double height;
    private Double weight;
    private String mothersMaidenName;
    private String oldMaritalStatusEnumId;
    private String maritalStatusTypeId;
    private String socialSecurityNumber;
    private String passportNumber;
    private Date passportExpireDate;
    private Double totalYearsWorkExperience;
    private String comments;
    private String employmentStatusEnumId;
    private String residenceStatusEnumId;
    private String occupation;
    private Double yearsWithEmployer;
    private Double monthsWithEmployer;
    private String existingCustomer;
    private String cardId;
    private String preferredCurrencyUomId;
    private String description;
    private String externalId;
    private String statusId;
}
