/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePartyRelationship changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePartyRelationship service.
 * Generated from OFBiz service definition; default-entity-name=PartyRelationship.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePartyRelationshipRequest extends RequestBase {

    private String partyIdFrom;
    private String partyIdTo;
    private String roleTypeIdFrom;
    private String roleTypeIdTo;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String statusId;
    private String relationshipName;
    private String securityGroupId;
    private String priorityTypeId;
    private String partyRelationshipTypeId;
    private String permissionsEnumId;
    private String positionTitle;
    private String comments;
}
