/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updatePartyInvitation changes.
 */
package com.landawn.ofbiz.model.party;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updatePartyInvitation service.
 * Generated from OFBiz service definition; default-entity-name=PartyInvitation.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdatePartyInvitationRequest extends RequestBase {

    private String partyInvitationId;
    private String partyIdFrom;
    private String partyId;
    private String toName;
    private String emailAddress;
    private String statusId;
    private Timestamp lastInviteDate;
}
