#!/usr/bin/env python3
"""
One-shot transform: replace `@RequestBody Map<String, Object>` request bodies and
`ResponseEntity<Map<String, Object>>` return types in every controller method with the typed
DTOs generated by scripts/gen_controller_dtos.py.

For each controller method we:
  1. Read the preceding Javadoc's `<p>service: <name>` tag.
  2. Look for {ServiceName}Request.java and {ServiceName}Response.java under
     src/main/java/com/landawn/ofbiz/model/{controller-lc}/.
  3. If BOTH exist, rewrite:
       - `@RequestBody Map<String, Object> body` -> `@RequestBody <Req> request`
       - `ResponseEntity<Map<String, Object>>` -> `ResponseEntity<<Resp>>`
     Otherwise leave the signature alone.
  4. `@RequestParam Map<String, String> params` is preserved on input; only the return
     type is rewritten when the response DTO exists.
  5. Method bodies are NOT touched (stub controllers keep their `throw new
     UnsupportedOperationException()`; WorkeffortController's bodies were already wired
     manually in a prior step).

After rewriting method signatures, the import block is regenerated to include the typed
DTOs that are actually referenced.

Run after `gen_controller_dtos.py --all`.
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTROLLER_DIR = ROOT / "src" / "main" / "java" / "com" / "landawn" / "ofbiz" / "controller"
MODEL_DIR = ROOT / "src" / "main" / "java" / "com" / "landawn" / "ofbiz" / "model"

# Same registry as gen_controller_dtos.py (controller stem -> subpackage).
CONTROLLERS = [
    ("Accounting",    "accounting"),
    ("Commonext",     "commonext"),
    ("Content",       "content"),
    ("Humanres",      "humanres"),
    ("Manufacturing", "manufacturing"),
    ("Marketing",     "marketing"),
    ("Order",         "order"),
    ("Party",         "party"),
    ("Product",       "product"),
    ("Webtools",      "webtools"),
    ("Workeffort",    "workeffort"),
]

# CommonextController exposes services owned by other OFBiz components — `framework/common/
# servicedef/` doesn't actually define them. For each such service we look up the DTO in the
# owning component's subpackage rather than generating a duplicate. Services not listed here
# (and not present in framework/common's servicedef) leave their controller method Map-based.
#
# controller -> { service-name -> owning subpackage }
CROSS_COMPONENT_OWNERS: dict[str, dict[str, str]] = {
    "Commonext": {
        "updateFacility":        "product",
        "updatePartyGroup":      "party",
        "updateProdCatalog":     "product",
        "updateProductCategory": "product",
        "updateProductStore":    "product",
        "updateWebSite":         "content",
        "entityExportAll":       "webtools",
    },
}

SERVICE_TAG_RE = re.compile(r"<p>\s*service:\s*([A-Za-z_][A-Za-z0-9_.]*)")

# Match the start of a Spring controller method:
#   Javadoc (multi-line) -> @Mapping(...) -> public ResponseEntity<...> name(...) { ... }
# Captures: full method block (Javadoc + annotation + signature line + body).
# The un-typed stubs ALL use the literal return type `ResponseEntity<Map<String, Object>>`,
# so we hard-match it rather than try to balance nested `<...>`.
# Match EVERY @Mapping method, whether Map-typed or already-typed. The signature group is
# permissive so the rewriter can normalize: response type is one of `Map<String, Object>` or a
# `XxxResponse`; the request param is either `@RequestBody Map<String, Object> body`,
# `@RequestBody XxxRequest request`, `@RequestParam Map<String, String> params`, or empty.
# We rewrite the canonical form on every run so the script is idempotent and self-healing.
METHOD_RE = re.compile(
    r"(/\*\*[\s\S]*?\*/)\s*"                                          # 1: Javadoc
    r"(@(?:Get|Post|Put|Delete|Patch)Mapping[^\n]*)\n\s*"              # 2: mapping annotation
    r"public\s+ResponseEntity<([^>]+(?:>[^>]*)?)>\s+(\w+)\s*\(([^)]*)\)",  # 3,4,5: response type, method name, params
    re.MULTILINE,
)


def pascal(name: str) -> str:
    return name[0].upper() + name[1:] if name else ""


def resolve_dto_subpackage(controller_name: str, default_subpkg: str,
                           service_name: str) -> str:
    """Return the subpackage that owns the DTOs for (controller, service). Defaults to the
    controller's own subpackage; cross-component overrides come from CROSS_COMPONENT_OWNERS."""
    overrides = CROSS_COMPONENT_OWNERS.get(controller_name, {})
    return overrides.get(service_name, default_subpkg)


def dtos_available(subpkg: str, service_name: str) -> tuple[bool, bool]:
    """Return (has_request_dto, has_response_dto) under model/<subpkg>/."""
    dir_ = MODEL_DIR / subpkg
    req = dir_ / f"{pascal(service_name)}Request.java"
    resp = dir_ / f"{pascal(service_name)}Response.java"
    return req.exists(), resp.exists()


def rewrite_param_list(params: str, req_type: str | None) -> str:
    """Rewrite the params list, preserving @RequestParam-style params and swapping
    @RequestBody Map<String, Object> for the typed Request DTO when one exists."""
    if not req_type:
        # No typed request — revert to Map<String, Object> body if previously typed,
        # or leave a @RequestParam line alone.
        if "@RequestParam" in params:
            return params
        # Force Map shape so an earlier mis-typing is repaired.
        return "@RequestBody Map<String, Object> body"
    # Typed request available — replace whatever's there with the canonical @RequestBody form.
    # @RequestParam endpoints (test-style) keep their input untouched.
    if "@RequestParam" in params:
        return params
    return f"@RequestBody {req_type} request"


def regenerate_imports(src: str, used_dtos: set[tuple[str, str]]) -> str:
    """Replace the controller's existing model.* imports with a fresh, sorted set covering only
    the DTOs actually referenced. `used_dtos` is a set of (subpackage, ClassName) so cross-
    component imports work. Leaves all non-model imports alone."""
    # Strip every existing `import com.landawn.ofbiz.model...;` line.
    src = re.sub(r"^import com\.landawn\.ofbiz\.model[^;]*;\n", "", src, flags=re.MULTILINE)
    new_imports = ["import com.landawn.ofbiz.model.ResponseBase;"]
    for subpkg, cls in sorted(used_dtos):
        new_imports.append(f"import com.landawn.ofbiz.model.{subpkg}.{cls};")
    block = "\n".join(new_imports) + "\n"
    src = re.sub(r"(package com\.landawn\.ofbiz\.controller;\n\n)",
                 r"\1" + block, src, count=1)
    return src


def ensure_wrap_helper(src: str) -> str:
    """Inject the generic `wrap()` helper into the controller class body if not present."""
    if "private static <T extends ResponseBase> ResponseEntity<T> wrap(" in src:
        return src
    # WorkeffortController already has a typed wrap helper from the prior pass.
    helper = (
        "\n    /** 200/400 routing decided by the response DTO's envelope state. */\n"
        "    private static <T extends ResponseBase> ResponseEntity<T> wrap(T result) {\n"
        "        return com.landawn.ofbiz.service.ServiceResponse.isError(result)\n"
        "                ? ResponseEntity.status(org.springframework.http.HttpStatus.BAD_REQUEST).body(result)\n"
        "                : ResponseEntity.ok(result);\n"
        "    }\n"
    )
    # Insert after the class-opening brace + blank line.
    src = re.sub(r"(public class \w+ \{\n)", r"\1" + helper, src, count=1)
    return src


@dataclass
class WiringStats:
    methods_total: int = 0
    methods_typed: int = 0
    methods_partial: int = 0   # only response typed (no Request DTO)
    methods_skipped: int = 0


def process_controller(name: str, subpkg: str) -> WiringStats:
    stats = WiringStats()
    path = CONTROLLER_DIR / f"{name}Controller.java"
    src = path.read_text(encoding="utf-8")
    used_dtos: set[tuple[str, str]] = set()  # (subpackage, ClassName)

    def repl(m: re.Match) -> str:
        nonlocal stats
        stats.methods_total += 1
        javadoc, mapping, _curr_resp, method_name, params = (
            m.group(1), m.group(2), m.group(3), m.group(4), m.group(5))
        st = SERVICE_TAG_RE.search(javadoc)
        if not st:
            stats.methods_skipped += 1
            return m.group(0)
        svc = st.group(1)
        if "." in svc or svc == "unknown":
            stats.methods_skipped += 1
            return m.group(0)
        dto_subpkg = resolve_dto_subpackage(name, subpkg, svc)
        has_req, has_resp = dtos_available(dto_subpkg, svc)
        if not has_resp:
            # Canonicalize back to Map<String, Object> in case an earlier run mistyped it.
            stats.methods_skipped += 1
            new_params = rewrite_param_list(params, None)
            new_sig = (f"public ResponseEntity<Map<String, Object>> "
                       f"{method_name}({new_params})")
            return f"{javadoc}\n    {mapping}\n    {new_sig}"
        resp_cls = pascal(svc) + "Response"
        req_cls = pascal(svc) + "Request" if has_req else None
        new_params = rewrite_param_list(params, req_cls)
        new_sig = (f"public ResponseEntity<{resp_cls}> "
                   f"{method_name}({new_params})")
        used_dtos.add((dto_subpkg, resp_cls))
        if req_cls and "@RequestBody" in new_params:
            used_dtos.add((dto_subpkg, req_cls))
            stats.methods_typed += 1
        else:
            stats.methods_partial += 1
        return f"{javadoc}\n    {mapping}\n    {new_sig}"

    new_src = METHOD_RE.sub(repl, src)
    new_src = regenerate_imports(new_src, used_dtos)
    new_src = ensure_wrap_helper(new_src)
    # Now rewrite each method body: stub methods stay throwing, but the wrap() helper means
    # we'd ideally want `return wrap(...)` calls — the stubs can't call wrap() since there's
    # no service backing them. Leave their bodies alone.
    path.write_text(new_src, encoding="utf-8", newline="\n")
    return stats


def main() -> int:
    grand_total = 0
    grand_typed = 0
    grand_partial = 0
    grand_skipped = 0
    for name, subpkg in CONTROLLERS:
        if name == "Workeffort":
            # Already wired manually with typed bodies + a service; signature transform would
            # break the existing typed wiring. Skip.
            print(f"  {name}: skipped (already wired manually)")
            continue
        s = process_controller(name, subpkg)
        grand_total += s.methods_total
        grand_typed += s.methods_typed
        grand_partial += s.methods_partial
        grand_skipped += s.methods_skipped
        print(f"  {name}: {s.methods_total} methods -> "
              f"{s.methods_typed} fully typed, {s.methods_partial} response-only typed, "
              f"{s.methods_skipped} left as Map (no DTO)")
    print()
    print(f"Total: {grand_total} methods, {grand_typed} fully typed, "
          f"{grand_partial} response-only typed, {grand_skipped} left as Map.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
