/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for addTimesheetToInvoice changes.
 */
package com.landawn.ofbiz.model.workeffort;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the addTimesheetToInvoice service.
 * Generated from OFBiz service definition; default-entity-name=Timesheet.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class AddTimesheetToInvoiceResponse extends ResponseBase {

    private String timesheetId;
    private String invoiceId;
    private Integer linkedTimeEntries;
    private Integer invoiceItemsCreated;
}
