/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createWorkEffortAndPartyAssign changes.
 */
package com.landawn.ofbiz.model.workeffort;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createWorkEffortAndPartyAssign service.
 * Generated from OFBiz service definition; default-entity-name=WorkEffort.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateWorkEffortAndPartyAssignRequest extends RequestBase {

    private String workEffortTypeId;
    private String currentStatusId;
    private String workEffortPurposeTypeId;
    private String workEffortParentId;
    private String scopeEnumId;
    private Double priority;
    private Double percentComplete;
    private String workEffortName;
    private String showAsEnumId;
    private String sendNotificationEmail;
    private String description;
    private String locationDesc;
    private Timestamp estimatedStartDate;
    private Timestamp estimatedCompletionDate;
    private Timestamp actualStartDate;
    private Timestamp actualCompletionDate;
    private Double estimatedMilliSeconds;
    private Double estimatedSetupMillis;
    private String estimateCalcMethod;
    private Double actualMilliSeconds;
    private Double actualSetupMillis;
    private Double totalMilliSecondsAllowed;
    private Double totalMoneyAllowed;
    private String moneyUomId;
    private String specialTerms;
    private Double timeTransparency;
    private String universalId;
    private String sourceReferenceId;
    private String fixedAssetId;
    private String facilityId;
    private String infoUrl;
    private String recurrenceInfoId;
    private String tempExprId;
    private String runtimeDataId;
    private String noteId;
    private String serviceLoaderName;
    private Double quantityToProduce;
    private Double quantityProduced;
    private Double quantityRejected;
    private Double reservPersons;
    private Double reserv2ndPpperc;
    private Double reservNthPpperc;
    private String accommodationMapId;
    private String accommodationSpotId;
    private String workEffortId;
    private String partyId;
    private String roleTypeId;
    private String statusId;
    private String quickAssignPartyId;
    private String requirementId;
    private String communicationEventId;
}
