/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createWorkEffortKeywords changes.
 */
package com.landawn.ofbiz.model.workeffort;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createWorkEffortKeywords service.
 * Generated from OFBiz service definition; default-entity-name=WorkEffortKeyword.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateWorkEffortKeywordsRequest extends RequestBase {

    private String workEffortId;
    private String keyword;
    private Double relevancyWeight;
}
