/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createWorkEffortAssoc changes.
 */
package com.landawn.ofbiz.model.workeffort;

import com.landawn.ofbiz.model.ResponseBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createWorkEffortAssoc service.
 * Generated from OFBiz service definition; default-entity-name=WorkEffortAssoc.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateWorkEffortAssocResponse extends ResponseBase {

    private String workEffortIdFrom;
    private String workEffortIdTo;
    private String workEffortAssocTypeId;
    private Timestamp fromDate;
}
