/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createTimesheetForThisWeek changes.
 */
package com.landawn.ofbiz.model.workeffort;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createTimesheetForThisWeek service.
 * Generated from OFBiz service definition; default-entity-name=Timesheet.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateTimesheetForThisWeekRequest extends RequestBase {

    private String partyId;
    private String clientPartyId;
    private String statusId;
    private String approvedByUserLoginId;
    private String comments;
    private Timestamp requiredDate;
}
