/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteTimesheetRole changes.
 */
package com.landawn.ofbiz.model.workeffort;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the deleteTimesheetRole service.
 * Generated from OFBiz service definition; default-entity-name=TimesheetRole.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteTimesheetRoleResponse extends ResponseBase {

    private Integer deletedRows;
}
