/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteWorkEffort changes.
 */
package com.landawn.ofbiz.model.workeffort;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the deleteWorkEffort service.
 * Generated from OFBiz service definition; default-entity-name=WorkEffort.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteWorkEffortResponse extends ResponseBase {

    private String workEffortId;
}
