/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createSurveyQuestionOption changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createSurveyQuestionOption service.
 * Generated from OFBiz service definition; default-entity-name=SurveyQuestionOption.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateSurveyQuestionOptionResponse extends ResponseBase {

    private String surveyOptionSeqId;
}
