/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createBlogEntry changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createBlogEntry service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateBlogEntryRequest extends RequestBase {

    private byte[] uploadedFile;
    private String _uploadedFile_fileName;
    private String _uploadedFile_contentType;
    private String blogContentId;
    private String contentName;
    private String statusId;
    private String description;
    private String templateDataResourceId;
    private String articleData;
    private String summaryData;
}
