/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createSurveyQuestionAppl changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createSurveyQuestionAppl service.
 * Generated from OFBiz service definition; default-entity-name=SurveyQuestionAppl.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateSurveyQuestionApplRequest extends RequestBase {

    private String surveyId;
    private String surveyQuestionId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private String surveyPageSeqId;
    private String surveyMultiRespId;
    private String surveyMultiRespColId;
    private String requiredField;
    private Double sequenceNum;
    private String externalFieldRef;
    private String withSurveyQuestionId;
    private String withSurveyOptionSeqId;
}
