/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createDataResource changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createDataResource service.
 * Generated from OFBiz service definition; default-entity-name=DataResource.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateDataResourceResponse extends ResponseBase {

    private String dataResourceId;
    private Object dataResource;
}
