/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createOrRemoveProductFeatureDataResource changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createOrRemoveProductFeatureDataResource service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateOrRemoveProductFeatureDataResourceRequest extends RequestBase {

    private String action;
    private String productFeatureId;
    private String dataResourceId;
}
