/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createSurveyMultiRespColumn changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createSurveyMultiRespColumn service.
 * Generated from OFBiz service definition; default-entity-name=SurveyMultiRespColumn.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateSurveyMultiRespColumnResponse extends ResponseBase {

    private String surveyMultiRespColId;
}
