/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createDocument changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createDocument service.
 * Generated from OFBiz service definition; default-entity-name=Document.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateDocumentRequest extends RequestBase {

    private String documentId;
    private String documentTypeId;
    private Timestamp dateCreated;
    private String comments;
    private String documentLocation;
    private String documentText;
    private byte[] imageData;
}
