/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createContentAssoc changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createContentAssoc service.
 * Generated from OFBiz service definition; default-entity-name=ContentAssoc.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateContentAssocRequest extends RequestBase {

    private String contentId;
    private String contentIdTo;
    private String contentAssocTypeId;
    private Timestamp thruDate;
    private String contentAssocPredicateId;
    private String dataSourceId;
    private Double sequenceNum;
    private String mapKey;
    private Double upperCoordinate;
    private Double leftCoordinate;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private Timestamp fromDate;
}
