/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createContent changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createContent service.
 * Generated from OFBiz service definition; default-entity-name=Content.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateContentRequest extends RequestBase {

    private String contentId;
    private String contentTypeId;
    private String ownerContentId;
    private String decoratorContentId;
    private String instanceOfContentId;
    private String dataResourceId;
    private String templateDataResourceId;
    private String dataSourceId;
    private String statusId;
    private String privilegeEnumId;
    private String serviceName;
    private String customMethodId;
    private String contentName;
    private String description;
    private String localeString;
    private String mimeTypeId;
    private String characterSetId;
    private Double childLeafCount;
    private Double childBranchCount;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private Timestamp thruDate;
    private String contentAssocPredicateId;
    private Double sequenceNum;
    private String mapKey;
    private Double upperCoordinate;
    private Double leftCoordinate;
    private String contentAssocTypeId;
    private String contentIdFrom;
    private String contentIdTo;
    private List<String> targetOperationList;
    private String targetOperationString;
    private List<String> contentPurposeList;
    private String contentPurposeString;
    private String skipPermissionCheck;
    private Boolean displayFailCond;
    private List<String> roleTypeList;
}
