/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createWebSiteRole changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createWebSiteRole service.
 * Generated from OFBiz service definition; default-entity-name=WebSiteRole.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateWebSiteRoleRequest extends RequestBase {

    private String partyId;
    private String roleTypeId;
    private String webSiteId;
    private Timestamp fromDate;
    private Timestamp thruDate;
    private Double sequenceNum;
}
