/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createContentAssoc changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.ResponseBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createContentAssoc service.
 * Generated from OFBiz service definition; default-entity-name=ContentAssoc.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateContentAssocResponse extends ResponseBase {

    private Timestamp fromDate;
}
