/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createElectronicText changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createElectronicText service.
 * Generated from OFBiz service definition; default-entity-name=ElectronicText.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateElectronicTextRequest extends RequestBase {

    private String dataResourceTypeId;
    private String dataTemplateTypeId;
    private String dataCategoryId;
    private String dataSourceId;
    private String statusId;
    private String dataResourceName;
    private String localeString;
    private String mimeTypeId;
    private String characterSetId;
    private String objectInfo;
    private String surveyId;
    private String surveyResponseId;
    private String relatedDetailId;
    private String isPublic;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private String dataResourceId;
    private List<String> targetOperationList;
    private List<String> contentPurposeList;
    private String skipPermissionCheck;
    private String roleTypeId;
    private String partyId;
    private byte[] uploadedFile;
    private String textData;
}
