/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createSurvey changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createSurvey service.
 * Generated from OFBiz service definition; default-entity-name=Survey.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateSurveyRequest extends RequestBase {

    private String surveyName;
    private String description;
    private String comments;
    private String submitCaption;
    private String responseService;
    private String isAnonymous;
    private String allowMultiple;
    private String allowUpdate;
    private String acroFormContentId;
}
