/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createSurveyResponse changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import java.util.Map;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the createSurveyResponse service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateSurveyResponseRequest extends RequestBase {

    private String partyId;
    private Timestamp responseDate;
    private Timestamp lastModifiedDate;
    private String referenceId;
    private String generalFeedback;
    private String orderId;
    private String orderItemSeqId;
    private String statusId;
    private Map<String, Object> answers;
    private String surveyResponseId;
    private String productStoreSurveyId;
    private String dataResourceId;
    private String surveyId;
}
