/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for createContent changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.ResponseBase;

import java.sql.Timestamp;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the createContent service.
 * Generated from OFBiz service definition; default-entity-name=Content.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class CreateContentResponse extends ResponseBase {

    private String contentId;
    private Timestamp thruDate;
    private String contentAssocPredicateId;
    private String dataSourceId;
    private Double sequenceNum;
    private String mapKey;
    private Double upperCoordinate;
    private Double leftCoordinate;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private String contentAssocTypeId;
    private String contentIdFrom;
    private String contentIdTo;
    private List<String> roleTypeList;
}
