/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteSurveyPage changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteSurveyPage service.
 * Generated from OFBiz service definition; default-entity-name=SurveyPage.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteSurveyPageRequest extends RequestBase {

    private String surveyId;
    private String surveyPageSeqId;
}
