/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for deleteSurveyQuestionOption changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the deleteSurveyQuestionOption service.
 * Generated from OFBiz service definition; default-entity-name=SurveyQuestionOption.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class DeleteSurveyQuestionOptionRequest extends RequestBase {

    private String surveyQuestionId;
    private String surveyOptionSeqId;
}
