/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for persistContentAndAssoc changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the persistContentAndAssoc service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class PersistContentAndAssocRequest extends RequestBase {

    private String contentTypeId;
    private String ownerContentId;
    private String decoratorContentId;
    private String instanceOfContentId;
    private String dataResourceId;
    private String templateDataResourceId;
    private String dataSourceId;
    private String statusId;
    private String privilegeEnumId;
    private String serviceName;
    private String customMethodId;
    private String contentName;
    private String description;
    private String localeString;
    private String mimeTypeId;
    private String characterSetId;
    private Double childLeafCount;
    private Double childBranchCount;
    private Timestamp createdDate;
    private String createdByUserLogin;
    private Timestamp lastModifiedDate;
    private String lastModifiedByUserLogin;
    private String drDataResourceId;
    private String drDataResourceTypeId;
    private String drDataTemplateTypeId;
    private String drDataCategoryId;
    private String drDataSourceId;
    private String drStatusId;
    private String drDataResourceName;
    private String drLocaleString;
    private String drMimeTypeId;
    private String drCharacterSetId;
    private String drObjectInfo;
    private String drSurveyId;
    private String drSurveyResponseId;
    private String drRelatedDetailId;
    private String drIsPublic;
    private String drCreatedDate;
    private String drCreatedByUserLogin;
    private String drLastModifiedDate;
    private String drLastModifiedByUserLogin;
    private String dataResourceTypeId;
    private String dataTemplateTypeId;
    private String dataCategoryId;
    private String dataResourceName;
    private String objectInfo;
    private String surveyId;
    private String surveyResponseId;
    private String relatedDetailId;
    private String isPublic;
    private String textData;
    private Timestamp thruDate;
    private String contentAssocPredicateId;
    private Double sequenceNum;
    private String mapKey;
    private Double upperCoordinate;
    private Double leftCoordinate;
    private String contentIdStart;
    private String caContentId;
    private String caContentIdTo;
    private String caContentAssocTypeId;
    private String caFromDate;
    private String caThruDate;
    private String caContentAssocPredicateId;
    private String caDataSourceId;
    private String caSequenceNum;
    private String caMapKey;
    private String caUpperCoordinate;
    private String caLeftCoordinate;
    private String caCreatedDate;
    private String caCreatedByUserLogin;
    private String caLastModifiedDate;
    private String caLastModifiedByUserLogin;
    private String contentId;
    private String rootDir;
    private List<String> targetOperationList;
    private List<String> contentPurposeList;
    private String targetOperationString;
    private String contentPurposeString;
    private byte[] imageData;
    private String _imageData_contentType;
    private String _imageData_fileName;
    private String deactivateExisting;
    private String forceElectronicText;
    private Boolean displayFailCond;
    private List<String> roleTypeList;
}
