/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeMimeTypeHtmlTemplate changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeMimeTypeHtmlTemplate service.
 * Generated from OFBiz service definition; default-entity-name=MimeTypeHtmlTemplate.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveMimeTypeHtmlTemplateRequest extends RequestBase {

    private String mimeTypeId;
}
