/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeWebSiteContent changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.ResponseBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Response DTO for the removeWebSiteContent service.
 * Generated from OFBiz service definition; default-entity-name=WebSiteContent.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveWebSiteContentResponse extends ResponseBase {

    // (no service-specific fields beyond the base envelope)
}
