/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for removeWebSitePathAlias changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the removeWebSitePathAlias service.
 * Generated from OFBiz service definition; default-entity-name=WebSitePathAlias.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class RemoveWebSitePathAliasRequest extends RequestBase {

    private String webSiteId;
    private String pathAlias;
    private Timestamp fromDate;
}
