/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateSiteRoles changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateSiteRoles service.
 * Generated from OFBiz service definition; default-entity-name=(none).
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateSiteRolesRequest extends RequestBase {

    private String partyId;
    private String contentId;
    private String blogUser;
    private String blogAuthor;
    private String blogEditor;
    private String blogAdmin;
    private String blogPublisher;
    private Timestamp blogUserFromDate;
    private Timestamp blogAuthorFromDate;
    private Timestamp blogEditorFromDate;
    private Timestamp blogAdminFromDate;
    private Timestamp blogPublisherFromDate;
}
