/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateContentApproval changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;

import java.sql.Timestamp;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateContentApproval service.
 * Generated from OFBiz service definition; default-entity-name=ContentApproval.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateContentApprovalRequest extends RequestBase {

    private String contentApprovalId;
    private String contentId;
    private String contentRevisionSeqId;
    private String partyId;
    private String roleTypeId;
    private String approvalStatusId;
    private Timestamp approvalDate;
    private Double sequenceNum;
    private String comments;
}
