/*
 * Generated by scripts/gen_controller_dtos.py — DO NOT EDIT BY HAND.
 * Re-run the script if the OFBiz service definition for updateDataResourceType changes.
 */
package com.landawn.ofbiz.model.content;

import com.landawn.ofbiz.model.RequestBase;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Request DTO for the updateDataResourceType service.
 * Generated from OFBiz service definition; default-entity-name=DataResourceType.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UpdateDataResourceTypeRequest extends RequestBase {

    private String dataResourceTypeId;
    private String parentTypeId;
    private String hasTable;
    private String description;
}
